(function(){var p=window.cfx,h=window.sfx,k={Version:"7.4.5649.31763"};p.treemap=k;k.TreeMapLayout={Naive:0,Squarified:1};var q=function e(){e._ic();this.d=this.h=null;this.k=this.g=0;this.j=this.f=null;this._0_1()};k.TreeMap=q;q.prototype={_0_1:function(){this.setLayout(1);this.e=!1;this.o();return this},getLayout:function(){return this.g},setLayout:function(e){this.g=e;switch(this.g){case 0:this.h=(new r)._0dP();break;case 1:this.h=(new t)._0dO()}},getRandomLocations:function(){return this.e},setRandomLocations:function(e){this.e=
e},getTemplate:function(){return null==this.d?null:this.d.t()},setTemplate:function(e){this.j=e;null==this.d&&(this.d=(new p.vector._Zt)._0_Zt());this.d.st(e)},p:function(e,g,a){if(this.k!=e.c&&!a){g=new h.U;this.k=e.c;if(null==this.f||this.f.length==e.d)this.f=Array(e.d);for(a=0;a<e.d;a++)this.f[a]=g.c(2)}},icX:function(e,g,a,b){switch(g){case 4:return 1;case 18:return 1;default:return null}},icY:function(e){return 1},icZ:function(e){return 142762241},o:function(){if(void 0!=p._Zt){var e=p.vector.eQ.i("TreeMap",
!0);null!=e&&this.setTemplate(e)}},m:function(e,g,a){var b=1;2==e.m_highlightState&&(b=.25);g.v(e.c,a,b,0)},ic0:function(e,g,a){g=a.m_bDetecting;e.a=1;e.b=0;var b=new p.bh;a.bx(b);var b=a.a.c.iaI(),c=!1;g?(a.C=1,a.e=0,a.o=0,a.p=b):a.e=a.o;var d=(new u)._01dM(a,b);this.e&&this.p(d,a,g);this.h.b(d,a);for(var n=a.X,l=new h.e,m=0;m<b;m++){a.ak();d.g=h.a.d(a.K);d.h=d.g/d.e;this.e&&(d.f=0!=this.f[m]);a.e==a.p?d.b._cf(d.a):this.h.c(d);if(0!=d.g)if(d.c-=d.c*d.h,d.e-=d.g,a.aA(a.d,a.e,!1),a.U(!0),a.aF(a.d,
a.e),g){if(a.c.idS(a.A,d.b),a.c.idC(a.r,d.b),a.detectCheck()){c=!0;break}}else{var f=h.d.r(d.b);n&&(f.w*=a.a0,f.h*=a.a0,f.x+=(d.b.w-f.w)/2,f.y+=(d.b.h-f.h)/2);if(null==this.d||h.b.p(this.d.t()))a.c.idT(a.A,f),a.c.idD(a.r,f);else{for(var k=this.d.id().Sb();1==k.SK();){var q=k.SM();this.d.l(q,a,this,f)}this.m(a,this.d,h.d.r(d.b))}if(a.b.a.b){switch(a.b.a.g){case 0:l.x=f.x;break;case 2:l.x=f.g();break;case 1:l.x=h.i(f.x+f.g(),2)}switch(a.b.a.d){case 0:l.y=f.y;break;case 2:l.y=f.c();break;case 1:l.y=
h.i(f.y+f.c(),2)}a.aQ=!0;a.aV(l._nc(),null,0)}}a.aj(0,1)}this.h.d(d,a);c?(e.b=0,e.a=e.b):(a.Y-=b-1,a.e=a.p,null!=this.d&&this.d._dispose1(!1))},reset:function(){},ieO:function(e,g){this.g=g.ie7("Layout",this.g,1);var a=new h._p1(this.e);g.ie6(a,"RandomLocations",!1);this.e=a.a;a.a=this.j;g.ieX(a,"Template");this.j=a.a}};q._dt("treemap.TreeMap",h.SA,0,p.icW,p.ieN);var u=function g(){g._ic();this.h=0;this.b=new h.c;this.g=0;this.f=!1;this.c=this.d=0;this.a=new h.c;this.e=0};u.prototype={_i1:function(g,
a){this.a._cf(g.k);this.e=g.P;this.d=a;this.b._i();this.c=this.a.w*this.a.h;this.g=this.h=0;this.f=!0},_i:function(){this.h=0;this.b._i();this.g=0;this.f=!1;this.c=this.d=0;this.a._i();this.e=0},_01dM:function(g,a){this._i1(g,a);return this}};u._dt("CWTT",h.W,0);k=function a(){a._ic()};k.prototype={_0dN:function(){return this},d:function(a,b){},b:function(a,b){}};k._dt("CWTT",h.SA,0);var t=function b(){b._ic();this.e=this.l=this.g=this.m=this.r=0;this.n=null;this.i=!1;this.h=this.j=this.k=this.p=
this.q=this.f=0};t.prototype={_0dO:function(){this._bc._0dN.call(this);return this},v:function(b,c,d){this.j=this.k;for(var n=0,l=0;l<c;l++,b++)var m=this.t(b,l,c),m=h.a.o(m/d,d/m),n=h.a.o(m,n);return n},d:function(b,c){this.n=null},u:function(b,c){this.k=c.w>c.h?c.h:c.w;var d=h.D.c,n=1,l=0;this.f=this.h=0;for(var m=b;m<this.q;m++,n++){var f=this.o(m);this.h+=f;var l=this.r*this.h/this.k,k=this.v(b,n,l);if(1>k||k>d){this.h-=f;n--;break}this.f=h.a.k(l);d=k}return n},t:function(b,c,d){b=this.o(b);var k=
0;c==d-1?k=this.j:(k=h.a.k(b/this.h*this.k),this.j-=k);return k},o:function(b){b=this.n.getItem(this.p,b);return b=1E108==b||h.D.h(b)?0:h.a.d(b)},c:function(b){var c=b.a.w>b.a.h;this.g-this.l>=this.m&&(this.l=this.g,this.i=b.f,this.m=this.u(this.g,b.a),c?(b.b.w=this.f,this.i?(this.e=b.a.y,b.b.x=b.a.x):(this.e=b.a.c(),b.b.x=b.a.g()-this.f)):(b.b.h=this.f,this.i?(this.e=b.a.x,b.b.y=b.a.y):(this.e=b.a.g(),b.b.y=b.a.c()-this.f)),this.j=this.k);var d=this.t(this.g,this.g-this.l,this.m);c?(b.b.h=d,this.i?
(b.b.y=this.e,this.e+=d):(this.e-=d,b.b.y=this.e)):(b.b.w=d,this.i?(b.b.x=this.e,this.e+=d):(this.e-=d,b.b.x=this.e));this.g++;if(this.g-this.l>=this.m||this.g==b.d-1)c?(b.a.w-=this.f,this.i&&(b.a.x+=this.f)):(b.a.h-=this.f,this.i&&(b.a.y+=this.f))},b:function(b,c){this.p=c.d;this.n=c.a.c.iaP();this.r=b.c/b.e;this.q=b.d;this.l=this.m=this.g=0}};t._dt("CWTT",k,0);var r=function c(){c._ic()};r.prototype={_0dP:function(){this._bc._0dN.call(this);return this},c:function(c){c.b.sf(c.a.f());c.a.w>c.a.h?
(c.b.h=c.a.h,c.b.w=c.a.w*c.h,c.f?c.a.x+=c.b.w:c.b.x=c.a.g()-c.b.w,c.a.w-=c.b.w):(c.b.w=c.a.w,c.b.h=c.a.h*c.h,c.f?c.a.y+=c.b.h:c.b.y=c.a.c()-c.b.h,c.a.h-=c.b.h)}};r._dt("CWTT",k,0);void 0!==p.UserInterface&&p.UserInterface.prototype.galleryMap["1"].push("=treemap.TreeMap,TreeMap")})();
