(function(){var w=window.cfx,f=window.sfx,E={Version:"7.4.5649.31763"};w.funnel=E;var y=function F(){F._ic();this.b=this.c=0};y.prototype={_0dM:function(k,c){k.x==c.x?(this.b=k.x,this.c=f.D.e):(this.b=(c.y-k.y)/(c.x-k.x),this.c=c.y-this.b*c.x);return this},a:function(k){return 0==this.b?0:f.D.h(this.c)?this.b:(k-this.c)/this.b}};y._dt("CWGF",f.SA,0);var k=function c(){c._ic();this.t=null;this.r=!1;this.z=this.f=this.g=this.a=null;this.b=this.v=this.d=this.e=0;this._0_1()};E.Funnel=k;k.prototype={_0_1:function(){this.p=
4;this.m=-1;this.q=5;this.i=30;this.l=10;this.c=this.w=!0;this.n=this.h=!1;this.o=(new w.Line)._01_2(9);this.I();return this},getConic:function(){return this.r},setConic:function(c){this.r=c;this.j()},getFaces:function(){return this.p},setFaces:function(c){this.p=f.a.o(c,3);this.j()},getLabelInside:function(){return this.h},setLabelInside:function(c){this.h=c;this.j()},getLabelLine:function(){return this.o},getLabelLineAsSeries:function(){return this.n},setLabelLineAsSeries:function(c){this.n=c;this.j()},
getSeparation:function(){return-1!=this.m?this.m:this.q},setSeparation:function(c){this.m=c;this.j()},getTemplate:function(){return null==this.a?"":this.a.t()},setTemplate:function(c){this.z=c;null==c?this.a=null:(null==this.a&&(this.a=(new w._Zt)._0_Zt()),this.a.st(c));this.G()},getTipHeight:function(){return this.i},setTipHeight:function(c){this.i=c},getTipWidth:function(){return this.l},setTipWidth:function(c){this.l=c},K:function(c,b){},icX:function(c,b,a,f){switch(b){case 4:return 1;case 11:return this.C(a);
case 12:return!0;case 18:return 1}return null},icY:function(c){return 1},icZ:function(c){return 142622977},J:function(c,b){var a=f.i(b.x+b.g(),2),h=this.l*b.w/100;this.e=a-h/2;this.d=a+h/2;a=b.h-this.getSeparation()*(c.a.c.iaI()-1);this.b=b.c()-a*this.i/100;this.v=c.bH*this.i/100;a=this.c?b.y:b.c();this.g=(new y)._0dM((new f.e)._01e(b.x,a),(new f.e)._01e(this.e,this.b));this.f=(new y)._0dM((new f.e)._01e(b.g(),a),(new f.e)._01e(this.d,this.b))},I:function(){if(void 0!=w._Zt){var c=w.eQ.i("Funnel",
!0);null!=c&&this.setTemplate(c)}},H:function(c,b){var a=!1,h=b[0].y,g=b[2].y,d=b;if(c.bu<this.v||0==c.bH){if(h<this.b&&b[2].x==b[3].x)return d=f.e._ca(6),d[0]._i1(this.f.a(h),h),d[1]._i1(this.g.a(h),h),d[2]._i1(this.g.a(this.b),this.b),d[3]._i1(d[2].x,g),d[5]._i1(this.f.a(this.b),this.b),d[4]._i1(d[5].x,g),d;b[0]._i1(this.e,h);b[1]._i1(this.d,h);a=!0}c.aZ<this.v?(b[2]._i1(this.d,g),b[3]._i1(this.e,g)):a&&this.b<g?(d=f.e._ca(6),d[0]._i1(this.f.a(h),h),d[1]._i1(this.g.a(h),h),d[2]._i1(this.e,this.b),
d[3]._i1(this.e,g),d[4]._i1(this.d,g),d[5]._i1(this.d,this.b)):(b[0]._i1(this.f.a(h),h),b[1]._i1(this.g.a(h),h),b[2]._i1(this.g.a(g),g),b[3]._i1(this.f.a(g),g));return d},G:function(){this.q=5;if(null!=this.a){var c=this.a.bK();null!=c&&(c=c.a("cfxDefSeparation"),c=f.V.D(c,f.b),null!=c&&(this.q=f.u.e(c)))}},ic0:function(c,b,a){c.a=1;c.b=0;var h=a.g(256);h&&(a.bh=!0);c=a.a.c.iaI();b=a.k._nc();b.w-=a.a.p;b.y+=a.a.p;b.h-=a.a.p;if(a.b.a.b&&!this.h){for(var g=0,d=0;d<c;d++){a.K=a.am.getItem(a.d,d);var k=
a.bO(),k=a.c.idY(k,a.R).w,g=f.a.o(g,k)}g+=8;2!=a.b.a.g&&(b.x+=g);b.w-=g}var g=b.h,k=b.w,l=this.getSeparation(),q=(g-l*(c-1))*b.w/2,e=g/k,m=983040|a.b.l,u=!1;h?u=!0:(m|=134217728,u=!1);0!=l&&(m|=3145728);var n=0,v=0,p=0,d=0;this.c?(n=-g,v=-1,p=b.c(),d=b.y):(n=g,v=1,p=b.y,d=b.c());var r=new w.ba,x=new w.ba;r.b=b.x;r.a=d+v*l;r.c=0;x.b=b.g();x.a=p-v*l;x.c=a.a.i;var G=f.i(b.g()+b.x,2);this.c&&90<a.f.ib7()||!this.c&&90>=a.f.ib7()?(a.C=-1,a.o=c-1,a.e=a.o,a.p=0):(a.C=1,a.o=0,a.e=a.o,a.p=c-1);var h=h?this.p:
4,t=0,A=0,z=a.P,y=a.X;if(y){for(d=z=0;d<c;d++)a.aA(a.d,d,!1),t=a.am.getItem(a.d,d)*a.a0,z+=t;if(0==z)return}a.bH=z;this.J(a,b);for(d=a.bu=0;d<c;d++){a.ak();if(y){if(0==a.a0){a.aj(0,1);continue}a.K*=a.a0;A+=a.K}else A=a.G;a.aZ=A;if(0!=a.K&&1E108!=a.K){0>a.C?(this.w?t=g-A/z*g:(t=q-A*q/z,t=f.a.u(f.a.d(2*t*e))),x.a=r.a-v*l,r.a=p+v*t):(this.w?t=A/z*g:(t=A*q/z,t=f.a.u(f.a.d(2*t*e))),r.a=x.a+v*l,x.a=p+v*t);var t=this.c?b.y-x.a:b.c()-x.a,C=0;a.g(33554432)&&(C|=1);a.aA(a.d,a.e,!1);a.U(!0);a.aF(a.d,a.e);var D=
m;d==c-1&&(D|=3145728);u?this.r?a.f.ib_(a.c,r,x,a.A,a.r,null,D,C,n,t):a.f.icm(a.c,r,x,a.A,a.r,null,D,C,n,t,h):this.E(a.c,r._nc(),x._nc(),C,n,t,a);t=a.K/z;a.b.a.b&&this.F(a,k,g,r,x,G,p,t,b);a.bu=A}a.aj(0,1)}this.K(a,b);a.Y-=c-1;a.e=a.p;null!=this.a&&this.a._dispose1(!1)},F:function(c,b,a,h,g,d,B,l,q){if(!c.X){var e=new w.ba,m=c.b.a._nc();l=m.g;m=m.d;c.g(256)&&(l=0);switch(m){case 0:e.a=this.c?g.a:h.a;break;case 2:e.a=this.c?h.a:g.a;break;default:e.a=f.i(h.a+g.a,2)}h=c.bO();this.h?1!=l?(q=k.k(e.a-B,
f.i(b,2),a),e.b=(this.c?0==l:2==l)?d-q:d+q,e.b=2==l?e.b-f.i(c.aR,2):e.b+f.i(c.aR,2)):e.b=d:(b=d=0,2==l?(e.b=q.g(),b=-2,d=e.a>this.b?this.d:this.f.a(e.a),d+=4,l=0):(e.b=q.x,b=2,d=e.a>this.b?this.e:this.g.a(e.a),d-=4,l=2),0!=this.o.d?(q=f.m.b._nc(),this.n&&q._cf(c.r.d()),q=this.o.c(q._nc()),c.c.idt(q,d,e.a,e.b+b,e.a),q._d()):e.b=d,m=1);e.c=f.i(c.a.i,2);e=c.f.icl(e);h=c.a$(c.h,h);c.bP(h,e._nc(),l,m,this.h)}},E:function(c,b,a,h,g,d,B){var l=null,q=null,l=q=null,e=0,m=0,u=0,n=0,v=0,p=0,r=0,e=p=m=e=0,n=
new w.ba,v=new w.ba;n._cf(b);v._cf(a);q=w.ba._ca(4);l=w.ba._ca(4);w.ba._ca(4);n=f.i(b.b+a.b,2);v=f.i(b.a+a.a,2);p=f.i(b.c+a.c,2);h=0!=(h&8);e=0!=(b.b+a.b&1);h&&(k.y(b,n,v),k.y(a,n,v),b.b>a.b&&(r=new f._p2(b.b,a.b),k.B(r),b.b=r.a,a.b=r.b),e&&a.a--);r=a.a-b.a;e=a.b-b.b;m=a.c-b.c;e=f.i(e,2);m=f.i(m,2);if(0!=g){var x=0,y=0,x=k.k(d,e,g),y=k.k(d,m,g),t=new f._p1(u);k.u(t,4,n,a.a,p,e-x,m-y,q,-1);u=t.a;x=k.k(d+r,e,g);y=k.k(d+r,m,g);t.a=u;k.u(t,4,n,b.a,p,e-x,m-y,l,-1)}else{d=new f._p1(u);k.u(d,4,n,a.a,p,e,
m,q,a.b);for(p=0;4>p;p++)l[p]._cf(q[p]);for(p=0;4>p;p++)l[p].a=b.a}e=4;d=null;if(0!=g&&(d=f.e._ca(e),d[0].x=q[1].b,d[0].y=a.a,d[1].x=q[3].b,d[1].y=a.a,d[2].y=b.a,d[2].x=l[3].b,d[3].x=l[1].b,d[3].y=b.a,h))for(p=0;p<e;p++)k.D(d[p],n,v);if(a.a!=b.a){d=this.H(B,d);u=f.d.b._nc();g=null;if(null!=this.a){for(c=this.a.id().Sb();1==c.SK();)switch(n=c.SM(),n.bA()){case "P":case "PointsPolygon":n.sa(d);break;case "X":n.sa(f.a.p(b.b,a.b));break;case "W":n.sa(f.a.d(a.b-b.b));break;case "Y":n.sa(f.a.p(b.a,a.a));
break;case "H":n.sa(f.a.d(a.a-b.a));break;case "G":case "Geometry":null==g&&(g=(new f.aA)._0aA(),g.z(d));n.sa(g);break;default:this.a.l(n,B,this,u)}b=f.d.b._nc();this.a.v(B.c,b,1,0)}else c.idQ(B.A,d),c.idx(B.r,d);null!=g&&g._d()}},j:function(){null!=this.t&&this.t.iag(16777248)},reset:function(){},ieO:function(c,b){var a=new f._p1(this.p);b.ie3(a,"Faces",4);this.p=a.a;a.a=this.m;b.ie3(a,"Separation",-1);this.m=a.a;a.a=this.i;b.ie5(a,"TipHeight",30);this.i=a.a;a.a=this.l;b.ie5(a,"TipWidth",10);this.l=
a.a;a.a=this.z;b.ieX(a,"Template");this.z=a.a;a.a=this.r;b.ie6(a,"Conic",!1);this.r=a.a;a.a=this.h;b.ie6(a,"LabelInside",!1);this.h=a.a;a.a=this.n;b.ie6(a,"LabelLineAsSeries",!1);this.n=a.a},ifa:function(c){this.t=c;this.o.ifa(this.t)},C:function(c){c=c.a;0==c.b&&(c.b=1);0==c.c&&(c.c=1);return null},toString:function(){return"Funnel"}};k.k=function(c,b,a){return f.i(c*b,a)};k.u=function(c,b,a,h,g,d,k,l,q){var e=0,m=0,u=0,n=u=m=0,v=0,p=0,r=0;b=f.a.o(f.a.d(b),2);b=f.a.p(b,4);r=6.28318530717959/b;n=
f.a.t(r);v=f.a.i(r);m=1;for(e=u=0;e<b;e++)l[e].a=h,l[e].b=a+f.a.k(d*u+.5),l[e].c=g+f.a.k(k*m+.5),p=m*v+u*n,u=u*v-m*n,m=p;c.a=r;if(-1!=q){m=f.u.c;u=-1;for(e=0;e<b;e++)l[e].b>m&&(u=e,m=l[e].b);if(-1!=u)for(e=0;e<b;e++)l[e].b==m&&(l[e].b=q)}return b};k.y=function(c,b,a){var f=c.b;c.b=b+(a-c.a);c.a=a-(b-f)};k.D=function(c,b,a){var f=c.x;c.x=b+(a-c.y);c.y=a-(b-f)};k.B=function(c){var b=c.a;c.a=c.b;c.b=b};k._dt("funnel.Funnel",f.SA,0,w.icW,w.ieN,w.ie_);void 0!==w.UserInterface&&w.UserInterface.prototype.galleryMap["1"].push("=funnel.Funnel,Funnel")})();
