(function(){var v=window.cfx,c=window.sfx,V={Version:"7.4.5649.31763"};v.rose=V;var p=function z(){z._ic()};p.prototype={_0dN:function(){return this}};p.h=function(z){return z*c.a.c/180};p.f=function(z){return c.a.k(z+1E-13)};p.e=function(z,h,a){var e=0;a&&(h.w<h.h?(e=c.i(h.h-h.w,2),h.h=h.w,h.y+=e):(e=c.i(h.w-h.h,2),h.w=h.h,h.x+=e));h.w-=h.w%4;h.h-=h.h%4;z.c=c.i(h.w,2);z.d=c.i(h.h,2);z.a=c.i(h.g()+h.x,2);z.b=c.i(h.y+h.c(),2)};p.d=function(c){for(;360<=c.a;)c.a-=360;for(;0>c.a;)c.a+=360};p.a=function(z,
h,a,e,b,l){var g;g=new c._p2(0,0);p.b(g,h,a,e,b,l);h=g.a;g=g.b;z.b=c.a.k(g+.5);z.a=c.a.k(h+.5)};p.b=function(z,h,a,e,b,l){var g=p.h(h);h=c.a.t(g);g=c.a.i(g);0==h&&0==g&&(h=0,g=1);z.b=l+e*h;z.a=b+a*g};p.c=function(c,h){var a=c._nc();c._cf(h);h._cf(a)};p._dt("CWGM",c.SA,0);var K=function h(){h._ic();this.i=!1;this.c=this.f=0;this.h=!1;this.e=null;this.d=this.b=0;this.g=!1};K.prototype={_0dO:function(){this.a=new c.e;return this},j:function(c){return this.i?this.f*c-this.d:-(this.d+this.f*c)}};K._dt("CWGR",
c.SA,0);var M=function a(){a._ic();this.j=this.a=this.b=null;this._0_1()};V.Rose=M;M.prototype={_0_1:function(){this.c=3;this.g=0;this.f=!0;this.e=90;this.v();return this},getCircular:function(){return 0!=(this.c&2)},setCircular:function(a){this.h(2,a)},getClockwise:function(){return 0!=(this.c&1)},setClockwise:function(a){this.h(1,a)},getInternalRadius:function(){return this.g},setInternalRadius:function(a){this.g=a},n:function(){return 0!=(this.c&4)},sn:function(a){this.h(4,a)},getSideBySide:function(){return this.f},
setSideBySide:function(a){this.f=a},getStartAngle:function(){return this.e},setStartAngle:function(a){this.e=a},getTemplate:function(){return null==this.b?null:this.b.t()},setTemplate:function(a){this.j=a;null==this.b&&(this.b=(new v._Zt)._0_Zt());this.b.st(a)},l:function(a){return this.a.j(a)},icX:function(a,c,b,l){switch(c){case 11:return this.o(b)}return null},icY:function(a){return 1},icZ:function(a){a=33579536;this.f&&(a|=128);return a},v:function(){if(void 0!=v._Zt){var a=v.eQ.i("Rose",!0);
null!=a&&this.setTemplate(a)}},ic0:function(a,e,b){e=b.a.c.iaI();this.a=(new K)._0dO();this.a.f=360/e;this.a.i=this.getClockwise();this.a.d=this.e;if(null!=this.b&&null!=this.b.t()){this.a.g=!0;for(var l=this.b.id().Sb();1==l.SK();)switch(l.SM().bA()){case "GT":case "GeometryTop":this.a.h=!0}}l=!1;0!=b.b.d&&(l=!0,this.a.e=Array(e));a.a=1;a.b=0;var g=b.k._nc();if(b.i.getVisible()){var k=new c.g,d=b.i.getLabelsCore();if(0!=d.Se()){var m=new c._p1(!1),d=d.ied(m,b.c,b.i.getFont(),!1);k._cf(d)}else d=
c.b.k(b.bk,"{0}",e),k._cf(b.c.idY(d,b.i.getFont()).e());g.m(-k.w,-k.h)}var f;f=new c._pN(0,0,0,0);p.e(f,g,!0);d=f.a;m=f.b;k=f.c;f=f.d;k=c.a.o(k,1);f=c.a.o(f,1);this.a.b=c.a.p(k,f);this.a.c=this.g*this.a.b/100;this.a.a._i1(d,m);m=0!=(b.j&2);d=0;d=0>=b.i.G?m?45:360/e:b.i.getStep();this.getClockwise()||(d=-d);g=this.u(b,g,d);if(this.q(b,d,g,this.getCircular())){g=!1;m=d=0;f=!1;for(var n=c.a.p(b.v,b.t),w=c.a.o(b.v,b.t);n<=w;n++)if(b.d=n,b.aL(n),!b.g(8192)){for(var q=b.N,H=b.J,x=(k-this.a.c)/(H-q),r=0;r<
e;r++){b.e=r;b.ak();b.aA(b.d,b.e,!1);b.U(!0);b.aU(b.d,b.e,!1);var t=b.K,A=0;f&&(A=this.a.e[r],t+=A);if(1E108==t)t=0;else if(t<=H&&t>=q&&!this.t(b,(A-q)*x,(t-q)*x,f)){d=n;m=r;g=!0;break}l&&(this.a.e[r]=t);b.aj(0,1)}l&&(f=!0);if(g)break}g?(b.d=d,b.e=m,a.b=0,a.a=a.b):(b.Y-=e-1,b.e=b.p);this.a=null}},u:function(a,e,b){var l=a.c,g=a.i,k=a.x(512),d=c.e._ca(3);d[0]._cf(this.a.a);var m=this.getCircular(),f=this.n(),n=a.bw(),w=c.a.d(360/b),q=0,H=0,x=0;f&&0!=n.a&&!k?(q=c.i(n.r,w+1),H=c.i(n.g,w+1),x=c.i(n.b,
w+1)):(f=!1,q=H=x=0);var r=g.c.a,t=null,A=0!=(a.u&8),u=null,U=null,E=null;A&&(t=(new v.c2)._01c2("PlotArea"),u=g.a7(r),U=(new v.c2)._01c2(v.c9.aa(g,"Line",-1,!0)),E=(new v.c2)._01c2(v.c9.aa(a.h,"Line",-1,!0)));var N=(new c.ar)._0ar(n),C=a.i.Q.c(c.m.b._nc()),W=a.h.Q.c(c.m.b._nc());!m||a.m_bDetecting||f||(A&&l.sidd(t),l.idM(N,e.x,e.y,2*this.a.b,2*this.a.b));var I=r.v,L=null;I&&(L=a.a_(r,4));var r=g.getLabelsCore(),T=r.Se(),O=g.getFont(),k=k?c.m.c():g.getTextColor()._nc(),F=0!=(a.j&2)?0:270,y=n._nc(),
B=N;l.sidd(null);var G,J,D=new c._p2(0,0);p.a(D,F,this.a.b,this.a.b,this.a.a.x,this.a.a.y);G=D.a;J=D.b;for(var P=0;P<w;P++){var Q=!a.m_bDetecting&&g.getVisible();Q&&(A&&l.sidd(g),M.r(a,w,r,T,O,k,G,J,F,P));F+=b;D.a=F;p.d(D);var F=D.a,R=0,S=0;D.Y(R,S);p.a(D,F,this.a.b,this.a.b,this.a.a.x,this.a.a.y);R=D.a;S=D.b;d[1].x=G;d[1].y=J;d[2].x=R;d[2].y=S;this.getClockwise()&&p.c(d[1],d[2]);if(!a.m_bDetecting&&(f&&(B=(new c.ar)._0ar(y)),A&&l.sidd(t),m?f&&l.idP(B,e,F-b,b):(l.idQ(B,d),l.sidd(U),l.idt(C,G,J,R,
S)),f&&B._d(),(0==P||I)&&Q)){J=G=null;if(0==P){if(J=E,G=W,4==a.aq||0==a.aq)I?(J=u,G=L):G=null}else J=u,G=L;if(null!=G){var Q=this.a.a.x,K=this.a.a.y;0!=this.a.c&&(D.Y(Q,K),p.b(D,F,this.a.c,this.a.c,this.a.a.x,this.a.a.y),Q=D.a,K=D.b);l.sidd(J);l.idt(G,Q,K,R,S);0!=P&&l.sidd(u)}}G=R;J=S;f&&(P>=c.i(w+1,2)?P==w?y._cf(n):y._cf(c.m.l(n.a,y.r+q,y.g+H,y.b+x)):y._cf(c.m.l(n.a,y.r-q,y.g-H,y.b-x)))}m&&!a.m_bDetecting&&(A&&l.sidd(U),l.idk(C,e.x,e.y,2*this.a.b,2*this.a.b));C._d();W._d();null!=L&&L._d();N._d();
return w},t:function(a,e,b,l){var g=this.a.c,k=(new c.aA)._0aA(),d=0,m=0;0==g?(d=a.b.v/100,m=(1-d)/2):(d=1,m=0);1!=a.ae&&(d/=a.ae,m+=a.I*d);var f=this.l(a.e+m),n=this.l(a.e+m+d),d=(f+n)/2,w=new c.f,q=new c.f,p=new c.f,x=new c.f,r=2*g,t=this.a.a.x-g,A=this.a.a.y-g,m=new c.f;p._cf(this.d(f,0));x._cf(this.d(n,0));var u=this.d(d,0);m._cf(this.d(d,b));var v=p.x-x.x,E=p.y-x.y;w._i1(m.x+v/2,m.y+E/2);q._i1(m.x-v/2,m.y-E/2);0!=e&&(u._cf(this.d(d,e)),p._i1(u.x+v/2,u.y+E/2),x._i1(u.x-v/2,u.y-E/2));u=null;this.a.h&&
(u=(new c.aA)._0aA());0!=g?(l?(k.r(w,q),k.r(q,x),k.r(x,p)):(k.f((new c.d)._02c(t,A,r,r),n,f-n),k.r(p,w),k.r(w,q)),k.E(),null!=u&&u.r(w,q)):(g=2*b,l?(k.g(this.a.a.x-e,this.a.a.y-e,2*e,2*e,f,n-f),k.g(this.a.a.x-b,this.a.a.y-b,g,g,n,f-n)):(k.u(this.a.a.x,this.a.a.y,x.x,x.y),0<b&&k.g(this.a.a.x-b,this.a.a.y-b,g,g,n,f-n),k.E()),null!=u&&u.g(this.a.a.x-b,this.a.a.y-b,g,g,n,f-n));if(this.a.g){e=c.d.b._nc();for(l=this.b.id().Sb();1==l.SK();)switch(f=l.SM(),f.bA()){case "G":case "Geometry":f.sa(k);break;case "GT":case "GeometryTop":f.sa(u);
break;case "SizeItem":f.sa(2*b);break;case "XItem":f.sa(this.a.a.x-b);break;case "YItem":f.sa(this.a.a.y-b);break;default:this.b.l(f,a,this,e)}this.b.v(a.c,e,1,0)}else a.c.idO(a.A,k),a.c.idv(a.r,k);if(a.m_bDetecting&&a.detectCheck())return a.j&=-2,!1;k._d();null!=u&&u._d();a.b.a.b&&(b=a.c.idg(),k=new c.aE,k.g(d+90,m),a.c.sidg(k),a.aV((new c.e)._01e(m.x,m.y),null,0),a.c.sidg(b));return!0},q:function(a,e,b,l){var g=a.N,k=a.J;if(g>=k)return!1;var d=a.h,m=d.o;if(0==(m&64)&&!a.m_bDetecting){0>=d.G&&d.calculateStep(a.a,
a.c,this.a.b,!0);var f=c.a.d(d.G),m=0==(m&1);if(0<f){var n=d.u,w=d.getFont(),q=a.x(512),H=d.getLabelsCore(),x=H.Se(),r=q?c.m.c():d.getTextColor()._nc(),t=d.c.a,q=t.v,A=a.a_(t,4),r=(new v.cG)._01cG(r._nc(),0,0),u=(this.a.b-this.a.c)/(k-g),K=a.c.idY(n.b(a.J),w).e().h,E=0!=(a.u&8),N=null;E&&(N=d.a7(t));for(var t=0!=t.w,C=0,M=0,I=g+f;I<=k;I+=f){var L=270,T=0,O=0,O=T=(I-g)*u+this.a.c;if(5>c.a.d(T-this.a.b))break;q&&l&&(E&&a.c.sidd(N),a.c.idk(A,this.a.a.x-O,this.a.a.y-O,2*O,2*O));for(var F=0;F<=b;F++){var y=
0,B=0,B=new c._p2(y,B);p.a(B,L,T,O,this.a.a.x,this.a.a.y);y=B.a;B=B.b;if(0!=F)if(q&&!l)E&&a.c.sidd(N),a.c.idt(A,C,M,y,B);else break;else m&&(C=null,0!=x?(C=p.f((I-g)/d.X+.1),C=H.iee(C)):C=n.b(I),C=a.a$(d,C),E&&a.c.sidd(d),r.n(a.c,w,C,(new c.e)._01e(y+4,B-c.i(K,2)))),t&&(E&&a.c.sidd(N),a.c.idt(A,y-2,B,y+2,B));L+=e;C=y;M=B}}r._d();A._d()}}return!0},d:function(a,e){var b=new c._p2(0,0);return this.p(b,a,e)},p:function(a,e,b){e=e*c.a.c/180;a.a=c.a.t(e);a.b=c.a.i(e);b+=this.a.c;e=this.a.a.x+b*a.b;a=this.a.a.y+
b*a.a;return(new c.f)._01e(e,a)},reset:function(){},ieO:function(a,e){this.c=e.ie7("Flags",this.c,3);var b=new c._p1(this.e);e.ie5(b,"StartAngle",90);this.e=b.a;b.a=this.g;e.ie4(b,"InternalRadius",0);this.g=b.a;b.a=this.f;e.ie6(b,"SideBySide",!0);this.f=b.a;b.a=this.j;e.ieX(b,"Template");this.j=b.a},h:function(a,c){this.c=c?this.c|a:this.c&~a},o:function(a){a.a.e=8;return null}};M.r=function(a,e,b,l,g,k,d,m,f,n){var p=0,q=0;270==f||90==f?p=1:90<=f&&270>=f&&(p=2);q=180<=f?2:0;f=null;f=0!=l?b.iee(n):
0!=(a.j&2)?a.i.u.b(360*n/e)+"\u00b0":a.i.u.b(0>=a.i.G?n+1:n*c.a.d(a.i.G));f=a.a$(a.i,f);e=(new v.cG)._01cG(k._nc(),p,q);e.n(a.c,g,f,(new c.e)._01e(d,m));e._d()};M._dt("rose.Rose",c.SA,0,v.icW,v.ieN);void 0!==v.UserInterface&&v.UserInterface.prototype.galleryMap["3"].push("=rose.Rose,Rose")})();
