(function(){var d=window.cfx,e=window.sfx,p={Version:"7.4.5649.31763"};d.heatmap=p;var m=function v(){v._ic();this.b=this.c=0;this._0_1()};p.ColorGradientStop=m;m.prototype={_0_1:function(){this.d=new e.m;this.a=new e.m;return this},getColor:function(){return this.d},setColor:function(d){d=e.m._t(d);this.d._cf(d);this.a._cf(d)},getOffset:function(){return this.c},setOffset:function(e){this.c=e},ieO:function(d,t){t.ieY("Color",this.d);var a=new e._p1(this.c);t.ie5(a,"Offset",0);this.c=a.a}};m._dt("heatmap.ColorGradientStop",
e.SA,0,d.ieN);var q=function t(){t._ic()};p.ColorGradientCollection=q;q.prototype={_0_1:function(){this.a=(new e._L)._0_L();return this},getCount:function(){return this.a.Se()},getItem:function(e){return this.a.So(e)},setItem:function(e,a){this.a.sSo(e,a)},add:function(e){this.a.Si(e)},clear:function(){this.a.clear()},e:function(d){var a=this.a.Se(),c=this.a.So(0);if(d==c.b)return c.a;for(var b=1;b<a;b++){var h=this.a.So(b),f=h.b;if(f==d)return h.a;if(f>d)return b=f-c.b,a=(d-c.b)/b,d=(f-d)/b,c=c.a._nc(),
h=h.a._nc(),e.m.k(c.r*d+h.r*a,c.g*d+h.g*a,c.b*d+h.b*a);c=h}return c.a},Sb:function(){return this.a.getEnumerator()},insert:function(e,a){this.a.Sl(e,a)}};q._dt("heatmap.ColorGradientCollection",e.SA,0,e.Sa);var u=function a(){a._ic();this.d=this.c=null;this.i=this.j=this.b=this.f=this.e=this.u=0;this.n=null;this.q=this.r=this.t=0;this._0_1()};p.HeatMap=u;u.prototype={_0_1:function(){this.a=(new q)._0_1();this.g=4;var a=new m;a.setColor(e.m.k(192,0,0));this.a.add(a);a=new m;a.setColor(e.m.k(0,192,
0));this.a.add(a);this.h=60;this.v();void 0!==d.motif?d._Em("heatmap",this,arguments):1<=arguments.length&&this.setStyle(arguments[0]);return this},getGradientStops:function(){return this.a},iei:function(){return!1},iej:function(){return null},getLegendHeight:function(){return this.g},setLegendHeight:function(a){this.g=a},iek:function(){return!0},getTemplate:function(){return null==this.d?null:this.d.q},setTemplate:function(a){this.n=a;null==this.d&&(this.d=(new d._Zt)._0_Zt());this.d.st(a)},ic2:function(a,
c,b,e){},iel:function(a){},ics:function(a){this.c=e.V.D(a,d.Chart);null!=this.c&&this.c.getLegendBox().getItemAttributes().getItemList(this.c.getSeries()).setVisible(!1);return!0},iem:function(a,c,b,e){this.e=0},ic3:function(a,c){return!0},ic4:function(a){this.l();return!1},ien:function(){return this.m()?1:this.g},ieo:function(a){return!1},icX:function(a,c,b,e){switch(c){case 11:return this.p(b);case 13:b.b=1}return null},getHighlightArgs:function(a,c,b){return!1},k:function(a){return this.c.getAxisY().getDataFormat().b(a)},
icY:function(a){return 1},icZ:function(a){return 33837056},iep:function(a,c,b,h,f){a.a=!0;f._cf(e.g.b);a=c.idY(this.k(this.f),b).e();this.m()&&(c=c.idY(this.k(this.b),b).e(),this.i=e.a.o(a.w,c.w),a.w=2*this.i+this.h,a.w=.8*h.w,this.h=a.w-2*this.i);return a},ict:function(a){return null},_iCommands:function(a){return!1},v:function(){if(void 0!=d._Zt){var a=d.eQ.i("HeatMap",!0);null!=a&&this.setTemplate(a)}},m:function(){var a=this.c.getLegendBox().ibP();return 3==a||1==a},ieq:function(a,c,b){a.a=null;
b=0==this.e?this.f:this.b;a.b=0==this.e||this.e==this.g-1?this.k(b):" ";a.c=null;a.d=this.e;var h=this.m(),f=this.g;h&&(f=1);if(this.e>=f)return!1;b=c.c;c.b.e=0;if(0==this.e){var g=c.H,d=c.H+f*c.aR-c.y,k=c.ao;b.sidd(null);var f=new e.c,r=new e.e,n=new e.e;h?(k+=this.i,n._i1(k,g),r._i1(k+this.h,g),f._i2(k,g,this.h,d-g+2)):(k-=6,r._i1(k,g),n._i1(k,d),f._i2(k,g+1,13,d-g-2));g=(new e.aC)._0aC(r,n,this.a.getItem(1).a,this.a.getItem(0).a);d=this.a.getCount();if(2<d){for(var k=(new e.ax)._01ax(d),r=e.m._ca(d),
n=Array(d),m=0;m<d;m++){var p=this.a.getItem(d-1-m),q=m;r[q]._cf(p.a);n[q]=1-p.b}k.sb(r);k.sc(n);g.sk(k)}c.c.idS(g,f);g._d();g=this.c.iK(13)._nc();g=b.ide()._Gv("fill",g,"LegendItem",0);g=(new e.ao)._01ao(g);b.idC(g,f);g._d();h&&(h=new e.at,h.sd(1),g=c.b.a.f,c=(new e.ar)._0ar(c.b.a.a),d=e.i(f.y+f.c(),2),b.idH(a.b,g,c,f.g()+4,d,h),k=this.k(this.b),h.sb(2),b.idH(k,g,c,f.x-4,d,h),a.b="",c._d(),h._d())}this.e++;return!0},ic0:function(a,c,b){c=b.c;a.b=1;a.a=0;a=0!=(b.u&8);if(b.e==b.o&&b.d==b.v){0==this.j&&
this.l();this.t=e.i(b.k.w,e.a.d(b.p-b.o)+1);this.u=e.i(b.k.h,e.a.d(b.t-b.v)+1);this.r=b.k.x;this.q=b.k.y;for(var h=!0,f=this.a.getCount(),g=c.idd(),l=0;l<f;l++){var k=this.a.getItem(l),m=k.d._nc();if(a){var n=(new d.c2)._01c2("HeatMap"+l.toString());c.sidd(n);m=c.ide()._Gv("fill",m,null,0)}k.a._cf(m);k.b=k.c;0!=k.b&&(h=!1)}a&&c.sidd(g);if(h&&1<f)for(g=h=1/(f-1),l=1;l<f;l++)k=this.a.getItem(l),k.b=g,g+=h}if(!(b.W||b.w<this.b||(l=b.h,h=b.i,f=e.a.k(l.valueToPixel(b.d)),l=e.a.k(l.valueToPixel(b.d+1)),
k=e.a.k(h.valueToPixel(b.e+.5)),h=e.a.k(h.valueToPixel(b.e+1.5)),l<f))){a&&(a=(new d.c2)._01c2(null),g=c.idc().ieD(b.c.idd()),a.d=g.ifi(1),a.e=g.ifi(0),c.sidd(a));a=this.a.e((b.w-this.b)/this.j)._nc();a=(new e.ar)._0ar(a);f=(new e.d)._02c(k,f,h-k,l-f);if(null!=this.d){b.A=a;for(l=this.d.id().Sb();1==l.SK();)k=l.SM(),this.d.l(k,b,this,f);this.d.v(c,f,1,0)}else c.idT(a,f);b.b.a.b&&(b.D=0,b.ap=0,b.n.b=f.x+f.w/2,b.n.a=f.y,b.L=f.y+f.h,b.O=1,b.ag=1,b.b.a.d=1,b.b.a.m=1);a._d()}},l:function(){var a=this.c.getAxisY(),
c=a.getLabels();c.clear();c.add("");for(var b=this.c.getSeries().Sb();1==b.SK();){var d=b.SM().getText();null==d&&(d="");c.add(d)}a.setMin(c.Se()-1);a.setMax(0);a.setLabelValue(1);a.setStyle(a.o|512);this.b=e.D.c;this.f=e.D.d;a=this.c.m;c=a.iaN();b=a.iaI();for(d=0;d<c;d++)for(var f=0;f<b;f++){var g=a.getItem(d,f);1E108!=g&&(this.b=e.a.p(this.b,g),this.f=e.a.o(this.f,g))}this.j=this.f-this.b},reset:function(){},ic5:function(a,c,b,d){return!1},ieO:function(a,c){var b=new e._p1(this.g);c.ie3(b,"LegendHeight",
3);this.g=b.a;b.a=this.n;c.ieX(b,"Template");this.n=b.a;this.a=c.ie8("GradientStops",this.a,"ColorGradientCollection",4)},p:function(a){a=a.a;a.e=8;0==this.j&&this.l();a.f=this.b;a.g=this.f;0==a.b&&(a.b=35);return null},ic6:function(a,c){return!1}};u._dt("heatmap.HeatMap",e.SA,0,d.icr,d.icW,d.ic1,d.ieh,d.i_n,d.ieN)})();
