(function(){var m=window.cfx,e=window.sfx,h={Version:"7.3.5518.20383"};m.treemap=h;h.TreeMapLayout={Naive:0,Squarified:1};var n=function f(){f._ic();this.d=this.h=null;this.k=this.g=0;this.j=this.f=null;this._0_1()};h.TreeMap=n;n.prototype={_0_1:function(){this.setLayout(1);this.e=!1;this.o();return this},getLayout:function(){return this.g},setLayout:function(f){this.g=f;switch(this.g){case 0:this.h=(new o)._0dP();break;case 1:this.h=(new p)._0dO()}},getRandomLocations:function(){return this.e},setRandomLocations:function(f){this.e=
f},getTemplate:function(){return null==this.d?null:this.d.t()},setTemplate:function(f){this.j=f;null==this.d&&(this.d=(new m.vector._Zt)._0_Zt());this.d.st(f)},p:function(f,j,a){if(this.k!=f.c&&!a){j=new e.U;this.k=f.c;if(null==this.f||this.f.length==f.d)this.f=Array(f.d);for(a=0;a<f.d;a++)this.f[a]=j.c(2)}},icV:function(f,e){switch(e){case 4:return 1;case 18:return 1;default:return null}},icW:function(){return 1},icX:function(){return 142762241},o:function(){if(void 0!=m._Zt){var f=m.vector.eP.i("TreeMap",
!0);null!=f&&this.setTemplate(f)}},m:function(f,e,a){var b=1;2==f.m_highlightState&&(b=0.25);e.v(f.c,a,b,0)},icY:function(f,j,a){j=a.m_bDetecting;f.a=1;f.b=0;var b=new m.bh;a.bq(b);var b=a.a.c.iaI(),c=!1;j?(a.C=1,a.e=0,a.o=0,a.p=b):a.e=a.o;var d=(new q)._01dM(a,b);this.e&&this.p(d,a,j);this.h.b(d,a);for(var l=a.V,i=new e.e,k=0;k<b;k++){a.aw();d.g=e.a.d(a.J);d.h=d.g/d.e;this.e&&(d.f=0!=this.f[k]);a.e==a.p?d.b._cf(d.a):this.h.c(d);if(0!=d.g)if(d.c-=d.c*d.h,d.e-=d.g,a.ay(a.d,a.e,!1),a.R(!0),a.aE(a.d,
a.e),j){if(a.c.idQ(a.A,d.b),a.c.idA(a.r,d.b),a.detectCheck()){c=!0;break}}else{var g=e.d.r(d.b);l&&(g.w*=a.aX,g.h*=a.aX,g.x+=(d.b.w-g.w)/2,g.y+=(d.b.h-g.h)/2);if(null!=this.d&&!e.b.p(this.d.t())){for(var h=this.d.id().Sb();!0==h.SI();)this.d.l(h.SK(),a,this,g);this.m(a,this.d,e.d.r(d.b))}else a.c.idR(a.A,g),a.c.idB(a.r,g);if(a.b.a.a){switch(a.b.a.h){case 0:i.x=g.x;break;case 2:i.x=g.g();break;case 1:i.x=e.i(g.x+g.g(),2)}switch(a.b.a.f){case 0:i.y=g.y;break;case 2:i.y=g.c();break;case 1:i.y=e.i(g.y+
g.c(),2)}a.aZ(i._nc(),!1,null)}}a.av(0,1)}this.h.d(d,a);c?(f.b=0,f.a=f.b):(a.W-=b-1,a.e=a.p,null!=this.d&&this.d._dispose1(!1))},reset:function(){},ieM:function(f,j){this.g=j.ie5("Layout",this.g,1);var a=new e._p1(this.e);j.ie4(a,"RandomLocations",!1);this.e=a.a;a=new e._p1(this.j);j.ieV(a,"Template");this.j=a.a}};n._dt("treemap.TreeMap",e.Sy,0,m.icU,m.ieL);var q=function j(){j._ic();this.h=0;this.b=new e.c;this.g=0;this.f=!1;this.c=this.d=0;this.a=new e.c;this.e=0};q.prototype={_i1:function(e,a){this.a._cf(e.k);
this.e=e.N;this.d=a;this.b._i();this.c=this.a.w*this.a.h;this.g=this.h=0;this.f=!0},_i:function(){this.h=0;this.b._i();this.g=0;this.f=!1;this.c=this.d=0;this.a._i();this.e=0},_01dM:function(e,a){this._i1(e,a);return this}};q._dt("CWTT",e.W,0);h=function a(){a._ic()};h.prototype={_0dN:function(){return this},d:function(){},b:function(){}};h._dt("CWTT",e.Sy,0);var p=function b(){b._ic();this.e=this.l=this.g=this.m=this.r=0;this.n=null;this.i=!1;this.h=this.j=this.k=this.p=this.q=this.f=0};p.prototype=
{_0dO:function(){this._bc._0dN.call(this);return this},v:function(b,c,d){this.j=this.k;for(var l=0,i=0;i<c;i++,b++)var k=this.t(b,i,c),k=e.a.o(k/d,d/k),l=e.a.o(k,l);return l},d:function(){this.n=null},u:function(b,c){this.k=c.w>c.h?c.h:c.w;var d=e.D.c,l=1,i=0;this.f=this.h=0;for(var k=b;k<this.q;k++,l++){var g=this.o(k);this.h+=g;var i=this.r*this.h/this.k,h=this.v(b,l,i);if(1>h||h>d){this.h-=g;l--;break}this.f=e.a.k(i);d=h}return l},t:function(b,c,d){var b=this.o(b),h=0;c==d-1?h=this.j:(h=e.a.k(this.k*
(b/this.h)),this.j-=h);return h},o:function(b){b=this.n.getItem(this.p,b);return b=1.0E108==b||e.D.h(b)?0:e.a.d(b)},c:function(b){var c=b.a.w>b.a.h;this.g-this.l>=this.m&&(this.l=this.g,this.i=b.f,this.m=this.u(this.g,b.a),c?(b.b.w=this.f,this.i?(this.e=b.a.y,b.b.x=b.a.x):(this.e=b.a.c(),b.b.x=b.a.g()-this.f)):(b.b.h=this.f,this.i?(this.e=b.a.x,b.b.y=b.a.y):(this.e=b.a.g(),b.b.y=b.a.c()-this.f)),this.j=this.k);var d=this.t(this.g,this.g-this.l,this.m);c?(b.b.h=d,this.i?(b.b.y=this.e,this.e+=d):(this.e-=
d,b.b.y=this.e)):(b.b.w=d,this.i?(b.b.x=this.e,this.e+=d):(this.e-=d,b.b.x=this.e));this.g++;if(this.g-this.l>=this.m||this.g==b.d-1)c?(b.a.w-=this.f,this.i&&(b.a.x+=this.f)):(b.a.h-=this.f,this.i&&(b.a.y+=this.f))},b:function(b,c){this.p=c.d;this.n=c.a.c.iaP();this.r=b.c/b.e;this.q=b.d;this.l=this.m=this.g=0}};p._dt("CWTT",h,0);var o=function c(){c._ic()};o.prototype={_0dP:function(){this._bc._0dN.call(this);return this},c:function(c){c.b.sf(c.a.f());c.a.w>c.a.h?(c.b.h=c.a.h,c.b.w=c.a.w*c.h,c.f?
c.a.x+=c.b.w:c.b.x=c.a.g()-c.b.w,c.a.w-=c.b.w):(c.b.w=c.a.w,c.b.h=c.a.h*c.h,c.f?c.a.y+=c.b.h:c.b.y=c.a.c()-c.b.h,c.a.h-=c.b.h)}};o._dt("CWTT",h,0);void 0!==m.UserInterface&&m.UserInterface.prototype.galleryMap["1"].push("=treemap.TreeMap,TreeMap")})();
