(function(){var d=window.sfx,p=window.cfx;p.pyramidVersion="7.4.5649.31763";var E=function v(){v._ic();this.h=null;this.f=this.a=this.e=this.g=!1};p.bv=E;E.prototype={_0bv:function(){this.d=4;this.b=5;return this},getConic:function(){return this.g},setConic:function(d){this.g=d;this.c()},getDistributeHeight:function(){return this.e},setDistributeHeight:function(d){this.e=d;this.c()},getFaces:function(){return this.d},setFaces:function(v){this.d=d.a.o(v,3);this.c()},getInverted:function(){return this.a},
setInverted:function(d){this.a=d;this.c()},getSeparation:function(){return this.b},setSeparation:function(d){this.b=d;this.c()},getShadow2D:function(){return this.f},setShadow2D:function(d){this.f=d;this.c()},icX:function(d,c,a,b){switch(c){case 11:return this.i(a);case 12:return this.a;case 18:return 1}return null},icY:function(d){return 1},icZ:function(d){return 142737665},ic0:function(v,c,a){v.a=1;v.b=0;v=a.g(256);c=new p.bh;a.bx(c);v&&(a.bh=!0);var b=a.a.c.iaI(),h=a.k._nc();h.w-=a.a.p;h.y+=a.a.p;
h.h-=a.a.p;var n=h.h,f=h.w,x=(n-this.b*(b-1))*h.w/2,t=n/f,m=983040|a.b.l;a.g(256)||(m|=134217728);0!=this.b&&(m|=3145728);var e=0,g=0,k=0,r=0;this.a?(e=-n,g=-1,k=h.c(),r=h.y):(e=n,g=1,k=h.y,r=h.c());var l=new p.ba,q=new p.ba;l.b=h.x;l.a=r+g*this.b;l.c=0;q.b=h.g();q.a=k-g*this.b;q.c=a.a.i;r=d.i(h.g()+h.x,2);this.a&&90<a.f.ib7()||!this.a&&90>=a.f.ib7()?(a.C=-1,a.o=b-1,a.e=a.o,a.p=0):(a.C=1,a.o=0,a.e=a.o,a.p=b-1);for(var B=v?this.d:4,u=0,z=0;z<b;z++)if(a.ak(),0!=a.K&&!p.c_.g(a.K)){0>a.C?(this.e?u=n-
a.G/a.P*n:(u=x-a.G*x/a.P,u=d.a.u(d.a.d(2*u*t))),q.a=l.a-g*this.b,l.a=k+g*u):(this.e?u=d.a.d(a.w)/a.P*n:(u=a.G*x/a.P,u=d.a.u(d.a.d(2*u*t))),l.a=q.a+g*this.b,q.a=k+g*u);var u=this.a?h.y-q.a:h.c()-q.a,A=0;v||this.f||(A|=32);a.g(33554432)&&(A|=1);a.aA(a.d,a.e,!1);a.U(!0);a.aF(a.d,a.e);var y=m;z==b-1&&(y|=3145728);this.g?a.f.ib_(a.c,l,q,a.A,a.r,null,y,A,e,u):a.f.icm(a.c,l,q,a.A,a.r,null,y,A,e,u,B);u=a.K/a.P;a.b.a.b&&this.j(a,c,f,n,l,q,r,k,u);a.aj(0,1)}a.Y-=b-1;a.e=a.p},j:function(v,c,a,b,h,n,f,x,t){var m=
new p.ba,e=v.b.a.g,g=v.b.a.d;v.g(256)&&1==e&&(e=0);switch(g){case 0:m.a=this.a?n.a:h.a;break;case 2:m.a=this.a?h.a:n.a;break;default:m.a=d.i(h.a+n.a,2)}1!=e?(a=p.bL.a(m.a-x,d.i(a,2),b),m.b=(this.a?0==e:2==e)?f-a:f+a,m.b=2==e?m.b-d.i(v.aR,2):m.b+d.i(v.aR,2)):m.b=f;m.c=d.i(v.a.i,2);f=v.f.icl(m);c=v.bz(c,t);c=v.a$(v.h,c);t=0;v.b.a.h&&(t=4096);e=(new p.cG)._02cG(v.b.a.a,e,g,t);v.a3(e,c,f,0);e._d()},c:function(){null!=this.h&&this.h.iag(16777248)},ieO:function(v,c){var a=new d._p1(this.d);c.ie3(a,"Faces",
4);this.d=a.a;a.a=this.f;c.ie6(a,"Shadow2D",!1);this.f=a.a;a.a=this.g;c.ie6(a,"Conic",!1);this.g=a.a;a.a=this.a;c.ie6(a,"Inverted",!1);this.a=a.a;a.a=this.b;c.ie3(a,"Separation",5);this.b=a.a;9<=c.ieS()&&(a.a=this.e,c.ie6(a,"DistributeHeight",!1),this.e=a.a)},ifa:function(d){this.h=d},i:function(d){d=d.a;0==d.b&&(d.b=17);0==d.c&&(d.c=1);return null}};E._dt("GP",d.SA,0,p.icW,p.ieN,p.ie_);var w=function c(){c._ic();this.q=this.v=this.x=!1;this._0_2()};p.VectorPyramid=w;w.prototype={_0_2:function(){this._bc._0eQ.call(this);
this.u=4;this.t=-1;this.w=5;return this},getConic:function(){return this.x},setConic:function(c){this.x=c;this.r()},getDistributeHeight:function(){return this.v},setDistributeHeight:function(c){this.v=c;this.r()},getFaces:function(){return this.u},setFaces:function(c){this.u=d.a.o(c,3);this.r()},m:function(){return"Pyramid"},getInverted:function(){return this.q},setInverted:function(c){this.q=c;this.r()},getSeparation:function(){return-1!=this.t?this.t:this.w},setSeparation:function(c){this.t=c;this.r()},
icX:function(c,a,b,d){switch(a){case 4:return 1;case 18:return 1;case 12:return this.q;case 11:return this.A(b)}return null},icY:function(c){return 1},icZ:function(c){return 142737665},k:function(){this.w=5;var c=this.a.j;null!=c&&(c=c.a("cfxDefSeparation"),c=d.V.D(c,d.b),null!=c&&(this.w=d.u.e(c)))},ic0:function(c,a,b){c.a=1;c.b=0;var h=b.g(256);c=!1;this.a.u()&&(this.e(),this.a.B(null,null),c=!0);a=new p.bh;b.bx(a);h&&(b.bh=!0);var n=b.a.c.iaI(),f=b.k._nc();f.w-=b.a.p;f.y+=b.a.p;f.h-=b.a.p;var x=
f.h,t=f.w,m=this.getSeparation(),e=(x-m*(n-1))*f.w/2,g=x/t,k=983040|b.b.l,r=!1;h?r=!0:(k|=134217728,r=!1);0!=m&&(k|=3145728);var l=0,q=0,B=0,u=0;this.q?(l=-x,q=-1,B=f.c(),u=f.y):(l=x,q=1,B=f.y,u=f.c());var z=new p.ba,A=new p.ba;z.b=f.x;z.a=u+q*m;z.c=0;A.b=f.g();A.a=B-q*m;A.c=b.a.i;u=d.i(f.g()+f.x,2);this.q&&90<b.f.ib7()||!this.q&&90>=b.f.ib7()?(b.C=-1,b.o=n-1,b.e=b.o,b.p=0):(b.C=1,b.o=0,b.e=b.o,b.p=n-1);var h=h?this.u:4,y=0,w=0,C=b.P,E=b.X;if(E){for(var D=C=0;D<n;D++)b.aA(b.d,D,!1),y=b.am.getItem(b.d,
D)*b.a0,C+=y;if(0==C)return}for(D=0;D<n;D++){b.ak();if(E){if(0==b.a0){b.aj(0,1);continue}b.K*=b.a0;w+=b.K}else w=b.G;if(0!=b.K&&1E108!=b.K){0>b.C?(this.v?y=x-w/C*x:(y=e-w*e/C,y=d.a.u(d.a.d(2*y*g))),A.a=z.a-q*m,z.a=B+q*y):(this.v?y=w/C*x:(y=w*e/C,y=d.a.u(d.a.d(2*y*g))),z.a=A.a+q*m,A.a=B+q*y);var y=this.q?f.y-A.a:f.c()-A.a,F=0;b.g(33554432)&&(F|=1);b.aA(b.d,b.e,!1);b.U(!0);b.aF(b.d,b.e);var G=k;D==n-1&&(G|=3145728);r?this.x?b.f.ib_(b.c,z,A,b.A,b.r,null,G,F,l,y):b.f.icm(b.c,z,A,b.A,b.r,null,G,F,l,y,
h):this.D(b.c,z._nc(),A._nc(),F,l,y,b);y=b.K/C;b.b.a.b&&this.E(b,a,t,x,z,A,u,B,y)}b.aj(0,1)}b.Y-=n-1;b.e=b.p;c&&this.a.F();this.a._dispose1(!1)},E:function(c,a,b,h,n,f,x,t,m){var e=new p.ba,g=c.b.a.g,k=c.b.a.d;c.g(256)&&(g=0);switch(k){case 0:e.a=this.q?f.a:n.a;break;case 2:e.a=this.q?n.a:f.a;break;default:e.a=d.i(n.a+f.a,2)}1!=g?(b=p.bL.a(e.a-t,d.i(b,2),h),e.b=(this.q?0==g:2==g)?x-b:x+b,e.b=2==g?e.b-d.i(c.aR,2):e.b+d.i(c.aR,2)):e.b=x;e.c=d.i(c.a.i,2);x=c.f.icl(e);a=c.bz(a,m);a=c.a$(c.h,a);c.bP(a,
x,g,k,!0)},D:function(c,a,b,h,n,f,x){var t=null,m=null,t=m=null,e=0,g=0,k=c=0,r=0,l=0,q=0,e=l=g=e=0,k=new p.ba,r=new p.ba;k._cf(a);r._cf(b);m=p.ba._ca(4);t=p.ba._ca(4);p.ba._ca(4);k=d.i(a.b+b.b,2);r=d.i(a.a+b.a,2);l=d.i(a.c+b.c,2);h=0!=(h&8);e=0!=(a.b+b.b&1);h&&(w.z(a,k,r),w.z(b,k,r),a.b>b.b&&(q=new d._p2(a.b,b.b),p.bL.c(q),a.b=q.a,b.b=q.b),e&&b.a--);q=b.a-a.a;e=b.b-a.b;g=b.c-a.c;e=d.i(e,2);g=d.i(g,2);if(0!=n){var B=0,u=0,B=p.bL.a(f,e,n),u=p.bL.a(f,g,n),z=new d._p1(c);w.y(z,4,k,b.a,l,e-B,g-u,m,-1);
c=z.a;B=p.bL.a(f+q,e,n);u=p.bL.a(f+q,g,n);z.a=c;w.y(z,4,k,a.a,l,e-B,g-u,t,-1)}else{f=new d._p1(c);w.y(f,4,k,b.a,l,e,g,m,b.b);for(l=0;4>l;l++)t[l]._cf(m[l]);for(l=0;4>l;l++)t[l].a=a.a}e=4;f=null;if(0!=n&&(f=d.e._ca(e),f[0].x=m[1].b,f[0].y=b.a,f[1].x=m[3].b,f[1].y=b.a,f[2].y=a.a,f[2].x=t[3].b,f[3].x=t[1].b,f[3].y=a.a,h))for(l=0;l<e;l++)w.C(f[l],k,r);if(b.a!=a.a){n=d.d.b._nc();c=null;for(k=this.a.id().Sb();1==k.SK();)switch(r=k.SM(),r.c){case "P":case "PointsPolygon":r.sa(f);break;case "X":r.sa(d.a.p(a.b,
b.b));break;case "W":r.sa(d.a.d(b.b-a.b));break;case "Y":r.sa(d.a.p(a.a,b.a));break;case "H":r.sa(d.a.d(b.a-a.a));break;case "G":case "Geometry":null==c&&(c=(new d.aA)._0aA(),c.z(f));r.sa(c);break;default:this.a.l(r,x,this,n)}this.c(x,this.a,d.d.b._nc());null!=c&&c._d()}},r:function(){null!=this.b&&this.b.iag(16777248)},j:function(c,a){var b=new d._p1(this.u);a.ie3(b,"Faces",4);this.u=b.a;b.a=this.x;a.ie6(b,"Conic",!1);this.x=b.a;b.a=this.q;a.ie6(b,"Inverted",!1);this.q=b.a;b.a=this.t;a.ie3(b,"Separation",
-1);this.t=b.a;b.a=this.v;a.ie6(b,"DistributeHeight",!1);this.v=b.a},A:function(c){c=c.a;0==c.b&&(c.b=17);0==c.c&&(c.c=1);return null},toString:function(){return"Pyramid"}};w.y=function(c,a,b,h,n,f,p,t,m){var e=0,g=0,k=0,r=k=g=0,l=0,q=0,w=0;a=d.a.o(d.a.d(a),2);a=d.a.p(a,4);w=6.28318530717959/a;r=d.a.t(w);l=d.a.i(w);g=1;for(e=k=0;e<a;e++)t[e].a=h,t[e].b=b+d.a.k(f*k+.5),t[e].c=n+d.a.k(p*g+.5),q=g*l+k*r,k=k*l-g*r,g=q;c.a=w;if(-1!=m){g=d.u.c;k=-1;for(e=0;e<a;e++)t[e].b>g&&(k=e,g=t[e].b);if(-1!=k)for(e=
0;e<a;e++)t[e].b==g&&(t[e].b=m)}return a};w.z=function(c,a,b){var d=c.b;c.b=a+(b-c.a);c.a=b-(a-d)};w.C=function(c,a,b){var d=c.x;c.x=a+(b-c.y);c.y=b-(a-d)};w._dt("VV",p.eQ,0,p.icW);void 0!==p.UserInterface&&p.UserInterface.prototype.galleryMap["1"].push("14,Pyramid")})();
