(function(){var w={Version:"7.1.5021.16204"};window.cfx.density=w;var t=window.cfx,a=window.sfx,u=function i(){i._ic();this.a=this.c=this.b=this.d=0};u.prototype={_i:function(){this.a=this.c=this.b=this.d=0},_0dM:function(){this._i();return this},f:function(){var i=this.a/100;if(-1==this.b)return i*=255,a.m.k(this.d,i,i,i);var c=this.b/60,d=this.c/100,j=a.a.j(c),c=c-j;0==(j&1)&&(c=1-c);var c=i*(1-d*c),g=0,b=0,e=0,d=a.a.n(0,a.a.o(i*(1-d),1)),c=a.a.n(0,a.a.o(c,1)),i=a.a.n(0,a.a.o(i,1));switch(j){case 6:case 0:g=
i;b=c;e=d;break;case 1:g=c;b=i;e=d;break;case 2:g=d;b=i;e=c;break;case 3:g=d;b=c;e=i;break;case 4:g=c;b=d;e=i;break;case 5:g=i,b=d,e=c}return a.m.k(this.d,255*g,255*b,255*e)},toString:function(){return a.b.j(null,"{0:f2},{1:f2},{2:f2}",this.b,this.c,this.a)},_cf:function(a){this.d=a.d;this.b=a.b;this.c=a.c;this.a=a.a;return this},_nc:function(){var a=new u;a._cf(this);return a}};u.g=function(a){return u.h(a.a,a.r,a.g,a.b)};u.h=function(i,c,d,j){var c=c/255,d=d/255,j=j/255,g=0,b=0,e=new u,b=a.a.o(c,
a.a.o(d,j)),g=a.a.n(c,a.a.n(d,j));g==b?(e.b=-1,e.c=0):(e.b=60*((c==b?3:d==b?5:1)-(c==b?d-j:d==b?j-c:c-d)/(g-b)),e.c=100*((g-b)/g));e.a=100*g;e.d=i;return e};u._dt("CWGDH",a.W,0);var C=function c(){c._ic()};C.prototype={_0dN:function(a,d,j){this.b=1;this.d=a;this.c=d;this.a=j;return this},ieO:function(c){switch(c){case 1:return"D";case 0:var c=this.a.n.getDataFormat(),d=this.a.m.getDataFormat();return a.b.j(null,"X {0} to {1}\nY {2} to {3}\nCount {4}",c.a(this.d),c.a(this.d+this.a.f),d.a(this.c),d.a(this.c+
this.a.d),this.b)}return null},ieP:function(){return null},mouseTrack:function(){return!1}};C._dt("CWGDD",a.Sy,0,t.ieN);var v=function d(){d._ic()};v.prototype={_0dO:function(a,j){this.b=a;this.a=j;return this},Sz:function(d){d=a.V.D(d,v);return null==d?!1:this.b==d.b&&this.a==d.a},SA:function(){return this.b+this.a},Sw:function(a){return this.b==a.b&&this.a==a.a},d:function(a,j){this.b=a;this.a=j},toString:function(){return a.b.j(null,"{0}, {1}",this.b,this.a)}};v._dt("CWGDD",a.Sy,0,a.IEquatable_1);
var D=function j(){j._ic();this.a=this.b=null};D.prototype={_0dP:function(){return this}};D._dt("CWGDD",a.Sy,0);var A=function g(){g._ic();this.a=0};w.DensityColor=A;A.prototype={_0DensityColor:function(){this.b=new a.m;return this},getColor:function(){return this.b},setColor:function(g){g=a.m._t(g);this.b._cf(g)},getPosition:function(){return this.a},setPosition:function(a){this.a=a}};A._dt("CWGDD",a.Sy,0);var E=function b(){b._ic();this.m=this.n=this.j=null;this.d=this.e=this.k=this.f=this.g=this.l=
this.h=0;this._0Density()};w.Density=E;E.prototype={_0Density:function(){this.a=40;this.b=(new a._D)._0_D();this.i=this.c=!0;return this},getSize:function(){return this.a},setSize:function(a){this.a!=a&&(this.a=a,this.c=!0,null!=this.j&&this.j.iM())},p:function(b){if(this.c){this.c=!1;var e=b.a.b.iaH();this.n=b.j;this.m=b.h;this.g=b.j.l;this.l=b.j.o;this.e=b.h.l;this.k=b.h.o;this.f=a.a.d(this.l-this.g)/this.a;this.d=a.a.d(this.k-this.e)/this.a;var f=(new v)._0dO(0,0);this.b.clear();for(var p=b.e=
0;p<e;p++){b.aw();var q=b.u;f.d(a.a.j((b.aT-this.g)/this.f),a.a.j((q-this.e)/this.d));var l=null,l=new a._p1(l),q=this.b.tryGetValue(l,f),l=l.a;q?l.b++:(l=(new C)._0dN(this.g+f.b*this.f,this.e+f.a*this.d,this),this.b.v((new v)._0dO(f.b,f.a),l));this.h=a.a.n(this.h,l.b);b.an(0,1)}}},reset:function(){},icV:function(){return 1},ic1:function(){this.c=!0;return!1},icW:function(){return 12800},ieG:function(a){this.j=a},overrideWizardValidation:function(){},ic0:function(){return!0},icU:function(a,e,f){switch(e){case 11:return this.o(f)}return null},
ic2:function(){return!1},icX:function(b,e,f){b.b=a.a.d(f.o-f.m);b.a=0;this.p(f);var b=f.c,p=f.v._nc(),e=p.w/(this.a+1),q=p.h/(this.a+1),l=p.x,p=p.c();if(f.m_bDetecting)for(var z=f.m_xDetect,k=f.m_yDetect,x=this.b.Sb();!0==x.SI();){var o=x.SK(),m=o.k,n=l+m.b*e,m=p-(m.a+1)*q;if(z>=n&&k>=m&&z<=n+e&&k<=m+q){b.sida(o.v);b.idR(a.aj.G(),n,m,e,q);break}}else{var z=(new a._D)._0_D(),h=null;f.b.a.b=!1;f.e=0;f.d=0;f.aw();f.N(!1);o=a.V.D(f.x,a.ar);n=u.g(o.j())._nc();o=n._nc();o.a=20;n=n._nc();n.a=80;k=Array(2);
k[0]=(new A)._0DensityColor();k[1]=(new A)._0DensityColor();k[0].b._cf(o.f());k[0].a=0;k[1].b._cf(n.f());k[1].a=1;for(var x=k[k.length-1].b._nc(),v=this.b.Sb();!0==v.SI();){var o=v.SK(),m=o.k,n=l+m.b*e,m=p-(m.a+1)*q,t=o.v.b,B=0,r=0,h=new a._p1(h),r=z.tryGetValue(h,t),h=h.a;if(!r){r=t;f.P&&(r=1+(r-1)*f.bv);for(var B=r/this.h,h=!1,y=0;y<k.length;y++){var s=k[y];if(B>s.a){var h=s.b._nc(),r=k[y+1].b._nc(),s=(B-s.a)/(k[y+1].a-s.a),w=1-s,B=a.a.j(h.r*s+r.r*w),y=a.a.j(h.g*s+r.g*w),h=a.a.j(h.b*s+r.b*w);x._cf(a.m.j(B,
y,h));h=!0;break}}h||x._cf(k[k.length-1].b);h=(new D)._0dP();h.b=(new a.ar)._0ar(x);this.i&&(h.a=(new a.ao)._01ao(x));z.v(t,h)}b.sida(o.v);b.idR(h.b,n,m,e,q);this.i&&b.idB(h.a,n,m,e,q)}for(b=z.Sb();!0==b.SI();)e=b.SK().v,e.b._d(),null!=e.a&&e.a._d()}f.ak=1},icZ:function(){},ic3:function(){return!1},o:function(a){a.a.e=16;return null}};E._dt("CWGDD",a.Sy,0,t.icT,t.icY,t.ieF)})();
