(function(){var f=window.sfx,g=window.cfx;g.surfaceVersion="7.4.5649.31763";var p=function b(){b._ic();this.b=this.f=this.l=this.a=this.e=null;this.d=this.g=!1;this.p=this.k=this.c=0};g.bs=p;p.prototype={_0bs:function(){return this},getColors:function(){return this.a},setColors:function(b){null==b?this.a=null:(this.a=f.m._ca(b.length),b.Sd(this.a,0));this.j(560)},iei:function(){return!1},iej:function(){return null},getShowContourLines:function(){return this.g},setShowContourLines:function(b){this.g=
b;this.o()},getShowGridLines:function(){return this.d},setShowGridLines:function(b){this.d=b;this.o()},iek:function(){return null!=this.e?this.e.iT().h==this:!1},getStep:function(){return 0>this.c?0:this.c},setStep:function(b){this.c=b;this.j(560)},i:function(){return null==this.a||0==this.a.length},iel:function(b){},iem:function(b,c,a,e){e=this.ien();b.a=!0;c.v=e-1;c.t=0;a&&(b=new f._p2(c.v,c.t),g.bL.c(b),c.v=b.a,c.t=b.b);c.q=a?1:-1;c.d=c.v-c.q;c.aL(0);a?this.m(c.c,0,c.b.i,c.b.p._nc(),e):this.m(c.c,
0,c.b.p,c.b.i._nc(),e)},h:function(b,c,a){0>=this.c&&(this.c=-b.a3(),0<=this.c&&(this.c=-f.a.d((a-c)/10)));return f.a.d(this.c)},ien:function(){var b=this.e.iT().r,c,a;a=new f._p2(0,0);b.af(a,!0);c=a.a;a=a.b;c==a&&(c=b.q,a=b.r);c=this.h(b,c,a);return f.a.h((b.x-b.t)/c)},n:function(b,c,a,e,f,g){if(this.g&&!this.d)for(var k=0;k<e;k++){var h=(k+1)%e;a[h].a==a[k].a&&a[k].a==f&&c.icc(b,g,a[h].b,a[h].a,a[h].c,a[k].b,a[k].a,a[k].c)}},ieo:function(b){return!1},v:function(b,c,a,e,l,m,k){if(-1!=e&&-1!=l&&-1!=
m&&-1!=k){var h=b.f,d=g.ba._ca(4),q=g.ba._ca(8),v=b.t<b.v?-1:1,x=b.n.c+g.bL.a(b.al,b.d,b.a.g),v=x-v*(b.al+f.i(b.al,b.a.g)+1);d[0].b=a;d[0].a=l;d[0].c=x;d[1].b=a;d[1].a=m;d[1].c=v;d[2].b=c;d[2].a=k;d[2].c=v;d[3].b=c;d[3].a=e;d[3].c=x;l=d[0].a>d[1].a&&d[0].a>d[3].a&&d[2].a>d[1].a&&d[2].a>d[3].a||d[0].a<d[1].a&&d[0].a<d[3].a&&d[2].a<d[1].a&&d[2].a<d[3].a;k=b.h;var r=b.N,p=b.J,B=this.h(k,r,p),w=b.z;this.t();for(var y=0;y<this.k;y++){var t=this.q(y),t=(new f.ar)._0ar(t),z=this.d?this.f:(new f.ao)._0ao(t),
A=this.g&&!this.d?this.f:null,r=r+B;r>p&&(r=p);var u=w,w=k.ai(b.a,r);u++;if(l){d[1].b=a;d[1].a=m;d[1].c=v;var n=g.bQ.P(d,q,w,u,3);0!=n&&(h.ick(b.c,q,n,t,z),this.n(b.c,h,q,n,u,A));d[1].b=c;d[1].a=e;d[1].c=x;n=g.bQ.P(d,q,w,u,3)}else n=g.bQ.P(d,q,w,u,4);0!=n&&(h.ick(b.c,q,n,t,z),this.n(b.c,h,q,n,u,A));t._d();this.d||z._d()}}},icX:function(b,c,a,e){switch(c){case 11:return this.r(a);case 13:a.b=1;a.j=!0;break;case 18:return 6}return null},q:function(b){if(this.i())return this.l.e();var c=this.a[b%this.a.length]._nc();
c.e()&&c._cf(this.e.iW(b%this.a.length));return c},icY:function(b){return 1},icZ:function(b){return 10==b?1079056136:1079064328},iep:function(b,c,a,e,l){l._cf(f.g.b);e=this.e.iT().r;l=e.Z();e=f.a.o(l.b(e.x).length,l.b(e.t).length);e=f.b.u(f.b.b,2*e,57);b.a=!0;return c.idY(e+" - ",a).e()},m:function(b,c,a,e,f){this.i()&&(0!=(b.ida()&8)&&(b=b.ide(),a=b._Gv("fill",a,"Attribute"+c,0),e=b._Gv("fill",e,"Attribute"+c+"Alt",0)),e.e()&&e._cf(g.bL.ag(a._nc(),0)),this.l=new g.b0(a,e,f))},ieq:function(b,c,a){b.b=
null;b.a=b.b;b.c=null;b.d=-1;if(c.d==c.t)return!1;c.d+=c.q;b.d=c.d;a=c.h;var e=this.h(a,c.N,c.J),g=a.Z(),m=new f.aQ,k=f.a.o(g.b(a.x).length,g.b(a.t).length),h=a.t+e*c.d,h=g.b(h),h=f.b.u(h,k,32);m.e(h);m.e(" - ");h=a.t+e*(c.d+1);h=g.b(h);h=f.b.u(h,k,32);m.e(h);b.b=m.toString();c.b.e=0;c.b.i._cf(this.q(c.d));c.U(!0);return!0},ic0:function(b,c,a){var e=c=0;if(a.aS){if(null==this.b||this.b.length!=a.a.g+1)this.b=f.e._ca(a.a.g+1);c=this.h(a.h,a.N,a.J);this.k=f.a.d(f.a.h((a.J-a.N)/c));0!=(a.u&8)&&(a.bh=
!0)}0==a.d&&a.e==a.o&&(this.m(a.c,a.d,a.b.i,a.b.p._nc(),this.k),this.f=this.d||this.g?a.r.n():null);c=a.n.b;e=a.E?a.H:-1;if(a.E&&a.d!=a.v&&a.e!=a.o){var g=0,g=a.t<a.v?-1:1;this.v(a,c,this.b[a.d].x,e,this.b[a.d].y,this.p,this.b[a.d-g].y)}this.p=this.b[a.d].y;this.b[a.d].x=c;this.b[a.d].y=e;b.a=1;b.b=0;a.d==a.t&&a.e==a.p&&this.u()},o:function(){this.j(32)},j:function(b){null!=this.e&&this.e.iag(b|16777216)},u:function(){null!=this.f&&(this.f._d(),this.f=null)},t:function(){this.i()&&this.l.d()},ieO:function(b,
c){var a=new f._p1(this.g);c.ie6(a,"ShowContourLines",!1);this.g=a.a;a.a=this.d;c.ie6(a,"ShowGridLines",!1);this.d=a.a;this.a=c.ie8("Colors",this.a,null,96)},ifa:function(b){this.e=b},r:function(b){b.a.e=64;return null}};p._dt("GS",f.SA,0,g.icW,g.ieh,g.i_n,g.ieN,g.ie_)})();
