(function(){var l=window.cfx,d=window.sfx,A=function s(){s._ic();this.h=null;this.f=this.a=this.e=this.g=!1};l.bB=A;A.prototype={_0bB:function(){this.d=4;this.b=5;return this},getConic:function(){return this.g},setConic:function(d){this.g=d;this.c()},getDistributeHeight:function(){return this.e},setDistributeHeight:function(d){this.e=d;this.c()},getFaces:function(){return this.d},setFaces:function(s){this.d=d.a.n(s,3);this.c()},getInverted:function(){return this.a},setInverted:function(d){this.a=
d;this.c()},getSeparation:function(){return this.b},setSeparation:function(d){this.b=d;this.c()},getShadow2D:function(){return this.f},setShadow2D:function(d){this.f=d;this.c()},icV:function(){return 1},icW:function(){return 142737665},ieG:function(d){this.h=d},icU:function(d,c,a){switch(c){case 11:return this.i(a);case 12:return this.a}return null},icX:function(s,c,a){s.a=1;s.b=0;s=a.g(256);c=new l.bh;a.bl(c);s&&(a.a$=!0);var b=a.a.b.iaH(),i=a.v._nc();i.w-=a.a.p;i.y+=a.a.p;i.h-=a.a.p;var j=i.h,f=
i.w,t=(j-this.b*(b-1))*i.w/2,o=j/f,k=983040|a.b.n;a.g(256)||(k|=134217728);0!=this.b&&(k|=3145728);var e=0,g=0,m=0,u=0;this.a?(e=-j,g=-1,m=i.c(),u=i.y):(e=j,g=1,m=i.y,u=i.c());var h=new l.ba,q=new l.ba;h.b=i.x;h.a=u+g*this.b;h.c=0;q.b=i.g();q.a=m-g*this.b;q.c=a.a.f;u=d.u.z(i.g()+i.x,2);this.a&&90<a.f.ib4()||!this.a&&90>=a.f.ib4()?(a.A=-1,a.m=b-1,a.e=a.m,a.o=0):(a.A=1,a.m=0,a.e=a.m,a.o=b-1);for(var w=s?this.d:4,n=0,v=0;v<b;v++)if(a.aw(),!(0==a.G||l.c6.d(a.G))){0>a.A?(this.e?n=j-a.Q/a.J*j:(n=t-a.Q*
t/a.J,n=d.a.r(d.a.d(2*n*o))),q.a=h.a-g*this.b,h.a=m+g*n):(this.e?n=d.a.d(a.u)/a.J*j:(n=a.Q*t/a.J,n=d.a.r(d.a.d(2*n*o))),h.a=q.a+g*this.b,q.a=m+g*n);var n=this.a?i.y-q.a:i.c()-q.a,r=0;!s&&!this.f&&(r|=32);a.g(33554432)&&(r|=1);a.ao(a.d,a.e,!1);a.N(!0);a.ax(a.d,a.e);var p=k;v==b-1&&(p|=3145728);this.g?a.f.ib8(a.c,h,q,a.x,a.n,null,p,r,e,n):a.f.icj(a.c,h,q,a.x,a.n,null,p,r,e,n,w);n=a.G/a.J;a.b.a.b&&this.j(a,c,f,j,h,q,u,m,n);a.an(0,1)}a.ak-=b-1;a.e=a.o},j:function(s,c,a,b,i,j,f,t,o){var k=new l.ba,e=s.b.a.h,
g=s.b.a.f;s.g(256)&&1==e&&(e=0);switch(g){case 0:k.a=this.a?j.a:i.a;break;case 2:k.a=this.a?i.a:j.a;break;default:k.a=d.u.z(i.a+j.a,2)}1!=e?(a=l.bR.a(k.a-t,d.u.z(a,2),b),k.b=(this.a?0==e:2==e)?f-a:f+a,k.b=2==e?k.b-d.u.z(s.aN,2):k.b+d.u.z(s.aN,2)):k.b=f;k.c=d.u.z(s.a.f,2);f=s.f.ici(k);c=s.bn(c._nc(),o);c=s.a3(s.h,c);o=0;s.b.a.i&&(o=4096);e=(new l.cE)._02cE(s.b.a.a,e,g,o);s.a6(e,c,f._nc());e._d()},c:function(){null!=this.h&&this.h.iaf(16777248)},i:function(d){d=d.a;0==d.b&&(d.b=17);0==d.c&&(d.c=1);
return null}};A._dt("CWGP",d.Sy,0,l.icT,l.ieF);var p=function c(){c._ic();this.n=this.q=this.t=!1;this._0VectorPyramid()};l.VectorPyramid=p;p.prototype={_0VectorPyramid:function(){this._bc._0VectorGallery.call(this);this.p=4;this.m=5;return this},getConic:function(){return this.t},setConic:function(c){this.t=c;this.o()},getDistributeHeight:function(){return this.q},setDistributeHeight:function(c){this.q=c;this.o()},getFaces:function(){return this.p},setFaces:function(c){this.p=d.a.n(c,3);this.o()},
k:function(){return"PyramidDefault"},getInverted:function(){return this.n},setInverted:function(c){this.n=c;this.o()},getSeparation:function(){return this.m},setSeparation:function(c){this.m=c;this.o()},icV:function(){return 1},icW:function(){return 142737665},icU:function(c,a,b){switch(a){case 4:return 1;case 11:return this.v(b)}return null},icX:function(c,a,b){c.a=1;c.b=0;var i=b.g(256),c=!1;this.a.t()&&(this.e(),this.a.D(null,null),c=!0);a=new l.bh;b.bl(a);i&&(b.a$=!0);var j=b.a.b.iaH(),f=b.v._nc();
f.w-=b.a.p;f.y+=b.a.p;f.h-=b.a.p;var t=f.h,o=f.w,k=(t-this.m*(j-1))*f.w/2,e=t/o,g=983040|b.b.n,m=!1;i?m=!0:(g|=134217728,m=!1);0!=this.m&&(g|=3145728);var u=0,h=0,q=0,p=0;this.n?(u=-t,h=-1,q=f.c(),p=f.y):(u=t,h=1,q=f.y,p=f.c());var n=new l.ba,v=new l.ba;n.b=f.x;n.a=p+h*this.m;n.c=0;v.b=f.g();v.a=q-h*this.m;v.c=b.a.f;p=d.u.z(f.g()+f.x,2);this.n&&90<b.f.ib4()||!this.n&&90>=b.f.ib4()?(b.A=-1,b.m=j-1,b.e=b.m,b.o=0):(b.A=1,b.m=0,b.e=b.m,b.o=j-1);var i=i?this.p:4,r=0,z=0,x=b.J,A=b.P;if(A){for(var y=x=0;y<
j;y++)b.ao(b.d,y,!1),r=b.ad.getItem(b.d,y)*b.aU,x+=r;if(0==x)return}for(y=0;y<j;y++){b.aw();if(A){if(0==b.aU){b.an(0,1);continue}b.G*=b.aU;z+=b.G}else z=b.Q;if(0!=b.G&&1.0E108!=b.G){0>b.A?(this.q?r=t-z/x*t:(r=k-z*k/x,r=d.a.r(d.a.d(2*r*e))),v.a=n.a-h*this.m,n.a=q+h*r):(this.q?r=z/x*t:(r=z*k/x,r=d.a.r(d.a.d(2*r*e))),n.a=v.a+h*this.m,v.a=q+h*r);var r=this.n?f.y-v.a:f.c()-v.a,B=0;b.g(33554432)&&(B|=1);b.ao(b.d,b.e,!1);b.N(!0);b.ax(b.d,b.e);var C=g;y==j-1&&(C|=3145728);m?this.t?b.f.ib8(b.c,n,v,b.x,b.n,
null,C,B,u,r):b.f.icj(b.c,n,v,b.x,b.n,null,C,B,u,r,i):this.x(b.c,n._nc(),v._nc(),B,u,r,b);r=b.G/x;b.b.a.b&&this.y(b,a,o,t,n,v,p,q,r)}b.an(0,1)}b.ak-=j-1;b.e=b.o;c&&this.a.C();this.a._dispose1(!1)},y:function(c,a,b,i,j,f,t,o,k){var e=new l.ba,g=c.b.a.h,m=c.b.a.f;c.g(256)&&(g=0);switch(m){case 0:e.a=this.n?f.a:j.a;break;case 2:e.a=this.n?j.a:f.a;break;default:e.a=d.u.z(j.a+f.a,2)}1!=g?(b=l.bR.a(e.a-o,d.u.z(b,2),i),e.b=(this.n?0==g:2==g)?t-b:t+b,e.b=2==g?e.b-d.u.z(c.aN,2):e.b+d.u.z(c.aN,2)):e.b=t;e.c=
d.u.z(c.a.f,2);t=c.f.ici(e);a=c.bn(a._nc(),k);a=c.a3(c.h,a);k=0;c.b.a.i&&(k=4096);g=(new l.cE)._02cE(c.b.a.a,g,m,k);c.a6(g,a,t._nc());g._d()},x:function(c,a,b,i,j,f,t){var o=null,k=null,o=k=null,e=0,g=0,m=0,u=c=0,h=0,q=0,e=h=g=e=0,c=new l.ba,u=new l.ba;c._cf(a);u._cf(b);k=l.ba._ca(4);o=l.ba._ca(4);l.ba._ca(4);c=d.u.z(a.b+b.b,2);u=d.u.z(a.a+b.a,2);h=d.u.z(a.c+b.c,2);i=0!=(i&8);e=0!=(a.b+b.b&1);i&&(p.u(a,c,u),p.u(b,c,u),a.b>b.b&&(g=new d._p2(a.b,b.b),l.bR.b(g),a.b=g.a,b.b=g.b),e&&b.a--);q=b.a-a.a;e=
b.b-a.b;g=b.c-a.c;e=d.u.z(e,2);g=d.u.z(g,2);if(0!=j){var w=0,n=0,w=l.bR.a(f,e,j),n=l.bR.a(f,g,j),m=new d._p1(m);p.r(m,4,c,b.a,h,e-w,g-n,k,-1);m=m.a;w=l.bR.a(f+q,e,j);n=l.bR.a(f+q,g,j);f=new d._p1(m);p.r(f,4,c,a.a,h,e-w,g-n,o,-1)}else{f=new d._p1(m);p.r(f,4,c,b.a,h,e,g,k,b.b);for(h=0;4>h;h++)o[h]._cf(k[h]);for(h=0;4>h;h++)o[h].a=a.a}e=4;f=null;if(0!=j&&(f=d.e._ca(e),f[0].x=k[1].b,f[0].y=b.a,f[1].x=k[3].b,f[1].y=b.a,f[2].y=a.a,f[2].x=o[3].b,f[3].x=o[1].b,f[3].y=a.a,i))for(h=0;h<e;h++)p.w(f[h],c,u);
if(b.a!=a.a){a=d.d.b._nc();for(b=this.a.id().Sb();!0==b.SI();)switch(j=b.SK(),j.c){case "P":case "PointsPolygon":j.sa(f);break;default:this.a.l(j,t,this,a)}this.c(t,this.a,d.d.b._nc())}},o:function(){null!=this.b&&this.b.iaf(16777248)},v:function(c){c=c.a;0==c.b&&(c.b=17);0==c.c&&(c.c=1);return null},toString:function(){return"Pyramid"}};p.r=function(c,a,b,i,j,f,l,o,k){for(var e=0,g=0,m=0,p=m=g=0,h=0,q=0,w=0,a=d.a.n(d.a.d(a),2),a=d.a.o(a,4),w=2*d.a.c/a,p=d.a.q(w),h=d.a.h(w),g=1,e=m=0;e<a;e++)o[e].a=
i,o[e].b=b+d.a.j(f*m+0.5),o[e].c=j+d.a.j(l*g+0.5),q=g*h+m*p,m=m*h-g*p,g=q;c.a=w;if(-1!=k){g=d.u.c;m=-1;for(e=0;e<a;e++)o[e].b>g&&(m=e,g=o[e].b);if(-1!=m)for(e=0;e<a;e++)o[e].b==g&&(o[e].b=k)}return a};p.u=function(c,a,b){var d=c.b;c.b=a+(b-c.a);c.a=b-(a-d)};p.w=function(c,a,b){var d=c.x;c.x=a+(b-c.y);c.y=b-(a-d)};p._dt("CWVV",l.VectorGallery,0,l.icT)})();
