(function(){var l={Version:"7.1.5021.16204"};window.cfx.heatmap=l;var f=window.cfx,d=window.sfx,j=function p(){p._ic();this.b=this.c=0;this._0ColorGradientStop()};l.ColorGradientStop=j;j.prototype={_0ColorGradientStop:function(){this.d=new d.m;this.a=new d.m;return this},getColor:function(){return this.d},setColor:function(f){f=d.m._t(f);this.d._cf(f);this.a._cf(f)},getOffset:function(){return this.c},setOffset:function(d){this.c=d}};j._dt("CWGC",d.Sy,0);var m=function q(){q._ic()};l.ColorGradientCollection=
m;m.prototype={_0ColorGradientCollection:function(){this.a=(new d._L)._0_L();return this},getCount:function(){return this.a.Se()},getItem:function(d){return this.a.So(d)},setItem:function(d,a){this.a.sSo(d,a)},add:function(d){this.a.Si(d)},clear:function(){this.a.clear()},e:function(f){var a=this.a.Se(),c=this.a.So(0);if(f==c.b)return c.a;for(var b=1;b<a;b++){var g=this.a.So(b),e=g.b;if(e==f)return g.a;if(e>f)return b=e-c.b,a=(f-c.b)/b,f=(e-f)/b,c=c.a._nc(),g=g.a._nc(),d.m.j(c.r*f+g.r*a,c.g*f+g.g*
a,c.b*f+g.b*a);c=g}return c.a},insert:function(d,a){this.a.Sl(d,a)}};m._dt("CWGC",d.Sy,0);var o=function a(){a._ic();this.c=null;this.o=this.p=this.l=this.h=this.i=this.b=this.e=this.d=this.m=0;this._0HeatMap()};l.HeatMap=o;o.prototype={_0HeatMap:function(){this.a=(new m)._0ColorGradientCollection();this.f=3;var a=new j;a.setColor(d.m.j(192,0,0));this.a.add(a);a=new j;a.setColor(d.m.j(0,192,0));this.a.add(a);this.g=60;return this},getGradientStops:function(){return this.a},iee:function(){return null},
ied:function(){return!1},ief:function(){return!0},getLegendHeight:function(){return this.f},setLegendHeight:function(a){this.f=a},j:function(a){return this.c.getAxisY().getDataFormat().a(a)},iei:function(){return this.n()?1:this.f},reset:function(){},icV:function(){return 1},ic1:function(){this.k();return!1},icW:function(){return 4096},_iCommands:function(){return!1},icp:function(a){this.c=d.V.D(a,f.Chart);this.c.getLegendBox().getItemAttributes().getItemList(this.c.getSeries()).setVisible(!1);return!0},
iej:function(){return!1},ieg:function(){},overrideWizardValidation:function(){},icq:function(){return null},ic0:function(){return!0},getHighlightArgs:function(){return!1},ic2:function(){return!1},icX:function(a,c,b){c=b.c;a.b=1;a.a=0;a=0!=(b.r&8);if(b.e==b.m&&b.d==b.p){0==this.i&&this.k();this.l=d.u.z(b.v.w,d.a.d(b.o-b.m)+1);this.m=d.u.z(b.v.h,d.a.d(b.q-b.p)+1);this.p=b.v.x;this.o=b.v.y;for(var g=!0,e=this.a.getCount(),i=0;i<e;i++){var h=this.a.getItem(i),n=h.d._nc();if(a){var k=(new f.c0)._01c0("HeatMap"+
i.toString());c.sida(k);n=c.a._Gv("fill",n,null,0)}h.a._cf(n);h.b=h.c;0!=h.b&&(g=!1)}if(g&&1<e){n=g=1/(e-1);for(i=1;i<e;i++)h=this.a.getItem(i),h.b=n,n+=g}}b.O||b.u<this.b||(e=b.e*this.l,i=b.d*this.m,a&&(a=(new f.c0)._01c0(null),h=c.ic_().iew(b.c.ida()),a.c=h.ieO(1),a.e=h.ieO(0),c.sida(a)),b=this.a.e((b.u-this.b)/this.i)._nc(),b=(new d.ar)._0ar(b),c.idS(b,e+this.p,i+this.o,this.l,this.m),b._d())},icZ:function(){},icU:function(a,c,b){switch(c){case 11:return this.q(b)}return null},ieh:function(){this.d=
0},ic3:function(){return!1},iek:function(a,c,b,g,e){a.a=!0;e._cf(d.g.b);a=c.idV(this.j(this.e),b).c();this.n()&&(c=c.idV(this.j(this.b),b).c(),this.h=d.a.n(a.w,c.w),a.w=2*this.h+this.g,a.w=0.8*g.w,this.g=a.w-2*this.h);return a},iel:function(a,c){a.a=null;var b=0==this.d?this.e:this.b;a.b=0==this.d||this.d==this.f-1?this.j(b):" ";a.c=null;a.d=this.d;var g=this.n(),b=this.f;g&&(b=1);if(this.d>=b)return!1;c.b.d=0;if(0==this.d){var e=c.K,i=c.K+b*c.aN-c.y,h=c.af;c.c.sida(null);var b=new d.c,f=new d.e,
k=new d.e;g?(h+=this.h,k._i1(h,e),f._i1(h+this.g,e),b._i2(h,e,this.g,i-e+2)):(h-=6,f._i1(h,e),k._i1(h,i),b._i2(h,e+1,16,i-e-2));e=(new d.aC)._0aC(f,k,this.a.getItem(1).a,this.a.getItem(0).a);i=this.a.getCount();if(2<i){for(var h=(new d.ax)._01ax(i),f=d.m._ca(i),k=Array(i),j=0;j<i;j++){var l=this.a.getItem(i-1-j),m=j;f[m]._cf(l.a);k[m]=1-l.b}h.sb(f);h.sc(k);e.sk(h)}c.c.idP(e,b);e._d();e=this.c.iK(3)._nc();e=(new d.ao)._01ao(e);c.c.idz(e,b);e._d();g&&(g=(new d.at)._0at(),g.sd(1),e=c.b.a.d,i=(new d.ar)._0ar(c.b.a.a),
h=d.u.z(b.y+b.c(),2),c.c.idE(a.b,e,i,b.g()+4,h,g),f=this.j(this.b),g.sb(2),c.c.idE(f,e,i,b.x-4,h,g),a.b="",i._d(),g._d())}this.d++;return!0},n:function(){var a=this.c.getLegendBox().ibM();return 3==a||1==a},k:function(){var a=this.c.getAxisY(),c=a.getLabels();c.clear();c.add("");for(var b=this.c.getSeries().Sb();!0==b.SI();){var g=b.SK().getText();null==g&&(g="");c.add(g)}a.setMin(0);a.setMax(c.Se()-1);a.setLabelValue(1);a.setStyle(a.j|512);this.b=d.D.b;this.e=d.D.c;a=this.c.r;c=a.iaM();b=a.iaH();
for(g=0;g<c;g++)for(var e=0;e<b;e++){var f=a.getItem(g,e);1.0E108!=f&&(this.b=d.a.o(this.b,f),this.e=d.a.n(this.e,f))}this.i=this.e-this.b},q:function(a){a=a.a;a.e=8;0==this.i&&this.k();a.f=this.b;a.g=this.e;0==a.b&&(a.b=35);return null}};o._dt("CWGH",d.Sy,0,f.ico,f.icT,f.icY,f.iec,f.i_n)})();
