(function(){var t=window.cfx,b=window.sfx,N={Version:"7.4.5649.31763"};t.density=N;var D=function n(){n._ic();this.a=this.c=this.b=this.d=0};D.prototype={_i:function(){this.a=this.c=this.b=this.d=0},f:function(){var n=this.a/100;if(-1==this.b)return n*=255,b.m.l(this.d,n,n,n);var d=this.b/60,f=this.c/100,r=b.a.k(d),d=d-r;0==(r&1)&&(d=1-d);var d=n*(1-f*d),p=0,q=0,a=0,f=b.a.o(0,b.a.p(n*(1-f),1)),d=b.a.o(0,b.a.p(d,1)),n=b.a.o(0,b.a.p(n,1));switch(r){case 6:case 0:p=n;q=d;a=f;break;case 1:p=d;q=n;a=f;
break;case 2:p=f;q=n;a=d;break;case 3:p=f;q=d;a=n;break;case 4:p=d;q=f;a=n;break;case 5:p=n,q=f,a=d}return b.m.l(this.d,255*p,255*q,255*a)},i:function(){return b.b.k(null,"{0:f2},{1:f2},{2:f2}",this.b,this.c,this.a)},_cf:function(b){this.d=b.d;this.b=b.b;this.c=b.c;this.a=b.a;return this},_nc:function(){var b=new D;b._cf(this);return b}};D.g=function(b){return D.h(b.a,b.r,b.g,b.b)};D.h=function(n,d,f,r){d/=255;f/=255;r/=255;var p=0,q=0,a=new D,q=b.a.p(d,b.a.p(f,r)),p=b.a.o(d,b.a.o(f,r));p==q?(a.b=
-1,a.c=0):(a.b=60*((d==q?3:f==q?5:1)-(d==q?f-r:f==q?r-d:d-f)/(p-q)),a.c=(p-q)/p*100);a.a=100*p;a.d=n;return a};D._dt("CWGDH",b.W,0);var z=function d(){d._ic()};z.prototype={_0dN:function(b,f){this.b=b;this.a=f;return this},Sw:function(b){return this.b==b.b&&this.a==b.a},SB:function(d){d=b.V.D(d,z);return null==d?!1:this.b==d.b&&this.a==d.a},SC:function(){return this.b+this.a},d:function(b,f){this.b=b;this.a=f},h:function(){return b.b.k(null,"{0}, {1}",this.b,this.a)}};z._dt("CWGDD",b.SA,0,b.IEquatable_1);
var E=function f(){f._ic();this.e=0};E.prototype={_0dO:function(b,r,p){this.b=1;this.d=b;this.c=r;this.a=p;return this},id5:function(){return null},id6:function(){return 16},f:function(b){switch(b){case "XFrom":return this.a.k.getDataFormat().b(this.d);case "XTo":return this.a.k.getDataFormat().b(this.d+this.a.f);case "YFrom":return this.a.j.getDataFormat().b(this.c);case "YTo":return this.a.j.getDataFormat().b(this.c+this.a.e);case "Count":return this.b.toString()}return null},ifi:function(f){switch(f){case 1:return"g,"+
this.e.toString();case 0:f=this.a.k.getDataFormat();var r=this.a.j.getDataFormat();return b.b.k(null,"X {0} to {1}\nY {2} to {3}\nCount {4}",f.b(this.d),f.b(this.d+this.a.f),r.b(this.c),r.b(this.c+this.a.e),this.b)}return null},ifj:function(b){return 1==b?0:null}};E._dt("CWGDD",b.SA,0,t.ifh);var K=function r(){r._ic();this.a=null};K.prototype={_0dP:function(){this.b=new b.d;return this}};K._dt("CWGDD",b.SA,0);var L=function p(){p._ic();this.a=this.b=this.c=null};L.prototype={_0dQ:function(){return this}};
L._dt("CWGDD",b.SA,0);var J=function q(){q._ic();this.a=0};J.prototype={_0dR:function(){this.b=new b.m;return this}};J._dt("CWGDD",b.SA,0);var m=function a(){a._ic();this.a=this.j=this.k=this.l=null;this.e=this.h=this.p=this.f=this.i=this.q=this.n=0;this._0_1()};N.Density=m;m.prototype={_0_1:function(){this.b=40;this.d=(new b._D)._0_D();this.c=(new b._L)._0_L();this.o=this.g=!0;this.x();return this},getSize:function(){return this.b},setSize:function(a){this.b!=a&&(this.b=a,this.g=!0,null!=this.l&&
this.l.iM())},getTemplate:function(){return null==this.a?"":this.a.t()},setTemplate:function(a){m.r=a;null==a?this.a=null:(null==this.a&&(this.a=(new t.vector._Zt)._0_Zt()),this.a.st(a))},ic2:function(a,b,c,g){},A:function(a){if(this.g){this.g=!1;var e=a.a.c.iaI();this.k=a.i;this.j=a.h;this.i=a.i.t;this.q=a.i.x;this.h=a.h.t;this.p=a.h.x;this.f=b.a.d(this.q-this.i)/this.b;this.e=b.a.d(this.p-this.h)/this.b;var c=(new z)._0dN(0,0);this.d.clear();this.c.clear();for(var g=a.e=0;g<e;g++){a.ak();var h=
a.w;c.d(b.a.k((a.aY-this.i)/this.f),b.a.k((h-this.h)/this.e));var k=null,k=new b._p1(k),h=this.d.tryGetValue(k,c),k=k.a;h?k.b++:(k=(new E)._0dO(this.i+c.b*this.f,this.h+c.a*this.e,this),k.e=this.c.Se(),this.c.Si(k),this.d.w((new z)._0dN(c.b,c.a),k));this.n=b.a.o(this.n,k.b);a.aj(0,1)}}},ic3:function(a,b){return!0},ic4:function(a){this.g=!0;return!1},u:function(a){0==a.getDataFormat().d&&a.getDataFormat().setDecimals(2);a.setStyle(a.o&-1073741825)},icX:function(a,e,c,g){a=null;switch(e){case 11:return this.w(c);
case 13:a=c;a.a=m.z("TipDensity");a.j=!0;a.b=1;break;case 14:a=c;e=b.V.D(a.k,E);if(null!=e)return e.f(a.g);break;case 16:return this.y(c);case 18:return 2}return null},icY:function(a){return 1},icZ:function(a){return 29184},y:function(a){try{var e=b.u.e(a);if(e<this.c.Se())return this.c.So(e)}catch(c){}return null},x:function(){if(void 0!=t._Zt){var a=t.vector.eQ.i("Density",!0);null!=a&&this.setTemplate(a)}},ic0:function(a,e,c){a.b=b.a.d(c.p-c.o);a.a=0;this.A(c);a=c.c;e=c.k._nc();var g=e.w/(this.b+
1),h=e.h/(this.b+1),k=e.x,m=e.c();if(c.m_bDetecting){e=c.m_xDetect;for(var x=c.m_yDetect,y=this.d.Sb();1==y.SK();){var A=y.SM(),v=A.k,F=k+v.b*g,v=m-(v.a+1)*h;if(e>=F&&x>=v&&e<=F+g&&x<=v+h){a.sidd(A.v);a.idU(b.aj.G(),F,v,g,h);break}}}else{e=(new b._D)._0_D();var l=null;c.b.a.b=!1;c.e=0;c.d=0;c.ak();c.U(!1);x=b.V.D(c.A,b.ar).j()._nc();0!=(a.ida()&8)&&(x=a.ide()._Gv("fill",x,"Attribute0",0));y=D.g(x);x=y._nc();x.a=20;y=y._nc();y.a=b.a.o(y.a,80);var u=Array(2);u[0]=(new J)._0dR();u[1]=(new J)._0dR();
u[0].b._cf(x.f());u[0].a=0;u[1].b._cf(y.f());u[1].a=1;for(var z=u[u.length-1].b._nc(),x=c.A,y=c.r,H=(new b.d)._02c(0,0,g,h),E=this.d.Sb();1==E.SK();){var A=E.SM(),v=A.k,F=k+v.b*g,v=m-(v.a+1)*h,w=A.v.b,I=0,B=0,l=new b._p1(l),B=e.tryGetValue(l,w),l=l.a;if(!B){B=w;c.X&&(B=1+(B-1)*c.bL);for(var I=B/this.n,l=!1,G=0;G<u.length;G++){var C=u[G];if(I>C.a){var l=C.b._nc(),B=u[G+1].b._nc(),C=(I-C.a)/(u[G+1].a-C.a),M=1-C,I=b.a.k(l.r*C+B.r*M),G=b.a.k(l.g*C+B.g*M),l=b.a.k(l.b*C+B.b*M);z._cf(b.m.k(I,G,l));l=!0;
break}}l||z._cf(u[u.length-1].b);l=(new L)._0dQ();l.c=(new b.ar)._0ar(z);this.o&&(l.a=(new b.ao)._01ao(z));null!=this.a&&(l.b=(new b._L)._0_L());e.w(w,l)}null!=this.a?(w=(new K)._0dP(),w.b._i2(F,v,g,h),w.a=A.v,l.b.Si(w)):(a.sidd(A.v),a.idU(l.c,F,v,g,h),this.o&&a.idE(l.a,F,v,g,h))}if(null!=this.a){h=this.a.bK();g=null;null!=h&&(g=h.a("background"),g=b.V.D(g,t.vector._Zt));if(null!=g)for(h=e.C().Sb();1==h.SK();){k=h.SM();for(A=g.id().Sb();1==A.SK();)m=A.SM(),g.l(m,c,this,H);for(k=k.b.Sb();1==k.SK();)w=
k.SM(),a.sidd(w.a),H._cf(w.b),g.v(a,H,1,0)}for(g=e.C().Sb();1==g.SK();){k=g.SM();c.A=k.c;c.r=k.a;for(h=this.a.id().Sb();1==h.SK();)m=h.SM(),this.a.l(m,c,this,H);for(h=k.b.Sb();1==h.SK();)w=h.SM(),a.sidd(w.a),H._cf(w.b),this.a.v(a,H,1,0)}c.A=x;c.r=y}for(a=e.Sb();1==a.SK();)e=a.SM().v,e.c._d(),null!=e.a&&e.a._d()}c.Y=1},reset:function(){},ic5:function(a,b,c,g){return!1},ieO:function(a,e){var c=new b._p1(this.b);e.ie3(c,"Size",40);this.b=c.a;c.a=m.r;e.ieX(c,"Template");m.r=c.a},ifa:function(a){this.l=
a;a=b.V.D(this.l,t.Chart);null!=a&&(this.u(a.getAxisX()),this.u(a.getAxisY()))},w:function(a){a.a.e=16;return null},ic6:function(a,b){return!1}};m.z=function(a){null==m.m&&(m.m=(new b.aO)._0aO("density.templates",null),m.t=m.m.b(b.aG.b(),!0,!0));return m.t.d(a)};m._dt("density.Density",b.SA,0,t.icW,t.ic1,t.ieN,t.ie_);b["density.templates"]={TipDensity:'<T xmlns:x="a"><g M="3,0,3,0"><g.CD><CD W="Auto"/><CD W="Auto"/><CD W="4"/><CD W="Auto"/></g.CD><g.RD><RD H="Auto"/><RD H="Auto"/><RD H="Auto"/></g.RD><TextBlock g.R="0" g.C="0" Text="{B SeriesTX}" M="0,0,4,0"/><TextBlock g.R="0" g.C="1" Text="{B DataXFrom}" FontWeight="Bold" HorizontalAlignment="Right"/><TextBlock g.R="0" g.C="3" Text="{B DataXTo}" FontWeight="Bold" HorizontalAlignment="Right"/><TextBlock g.R="1" g.C="0" Text="{B SeriesTY}" M="0,0,4,0"/><TextBlock g.R="1" g.C="1" Text="{B DataYFrom}" FontWeight="Bold" HorizontalAlignment="Right"/><TextBlock g.R="1" g.C="3" Text="{B DataYTo}" FontWeight="Bold" HorizontalAlignment="Right"/><TextBlock g.R="2" g.C="0" Text="Count:" M="0,0,4,0"/><TextBlock g.R="2" g.C="3" Text="{B DataCount}" FontWeight="Bold" HorizontalAlignment="Right"/></g></T>'};
void 0!==t.UserInterface&&(t.UserInterface.prototype.galleryMap["2"].push("+density.Density,Density"),t.UserInterface.prototype.galleryMap["density.Density"]=[{Text:"Size",Type:"Range",Min:20,Max:60,API:"Size"}])})();
