(function(){var d=window.sfx,l=window.cfx;l.pyramidVersion="7.3.5518.20383";var A=function q(){q._ic();this.h=null;this.f=this.a=this.e=this.g=!1};l.bv=A;A.prototype={_0bv:function(){this.d=4;this.b=5;return this},getConic:function(){return this.g},setConic:function(d){this.g=d;this.c()},getDistributeHeight:function(){return this.e},setDistributeHeight:function(d){this.e=d;this.c()},getFaces:function(){return this.d},setFaces:function(q){this.d=d.a.o(q,3);this.c()},getInverted:function(){return this.a},
setInverted:function(d){this.a=d;this.c()},getSeparation:function(){return this.b},setSeparation:function(d){this.b=d;this.c()},getShadow2D:function(){return this.f},setShadow2D:function(d){this.f=d;this.c()},icV:function(d,c,a){switch(c){case 11:return this.i(a);case 12:return this.a;case 18:return 1}return null},icW:function(){return 1},icX:function(){return 142737665},icY:function(q,c,a){q.a=1;q.b=0;q=a.g(256);c=new l.bh;a.bq(c);q&&(a.bc=!0);var b=a.a.c.iaI(),i=a.k._nc();i.w-=a.a.p;i.y+=a.a.p;
i.h-=a.a.p;var j=i.h,f=i.w,t=(j-this.b*(b-1))*i.w/2,o=j/f,k=983040|a.b.l;a.g(256)||(k|=134217728);0!=this.b&&(k|=3145728);var e=0,g=0,m=0,u=0;this.a?(e=-j,g=-1,m=i.c(),u=i.y):(e=j,g=1,m=i.y,u=i.c());var h=new l.ba,r=new l.ba;h.b=i.x;h.a=u+g*this.b;h.c=0;r.b=i.g();r.a=m-g*this.b;r.c=a.a.g;u=d.i(i.g()+i.x,2);this.a&&90<a.f.ib5()||!this.a&&90>=a.f.ib5()?(a.C=-1,a.o=b-1,a.e=a.o,a.p=0):(a.C=1,a.o=0,a.e=a.o,a.p=b-1);for(var w=q?this.d:4,n=0,v=0;v<b;v++)if(a.aw(),!(0==a.J||l.c_.f(a.J))){0>a.C?(this.e?n=
j-a.G/a.N*j:(n=t-a.G*t/a.N,n=d.a.u(d.a.d(2*n*o))),r.a=h.a-g*this.b,h.a=m+g*n):(this.e?n=d.a.d(a.w)/a.N*j:(n=a.G*t/a.N,n=d.a.u(d.a.d(2*n*o))),h.a=r.a+g*this.b,r.a=m+g*n);var n=this.a?i.y-r.a:i.c()-r.a,s=0;!q&&!this.f&&(s|=32);a.g(33554432)&&(s|=1);a.ay(a.d,a.e,!1);a.R(!0);a.aE(a.d,a.e);var p=k;v==b-1&&(p|=3145728);this.g?a.f.ib9(a.c,h,r,a.A,a.r,null,p,s,e,n):a.f.ick(a.c,h,r,a.A,a.r,null,p,s,e,n,w);n=a.J/a.N;a.b.a.a&&this.j(a,c,f,j,h,r,u,m,n);a.av(0,1)}a.W-=b-1;a.e=a.p},j:function(q,c,a,b,i,j,f,t,o){var k=
new l.ba,e=q.b.a.h,g=q.b.a.f;q.g(256)&&1==e&&(e=0);switch(g){case 0:k.a=this.a?j.a:i.a;break;case 2:k.a=this.a?i.a:j.a;break;default:k.a=d.i(i.a+j.a,2)}1!=e?(a=l.bL.a(k.a-t,d.i(a,2),b),k.b=(this.a?0==e:2==e)?f-a:f+a,k.b=2==e?k.b-d.i(q.aP,2):k.b+d.i(q.aP,2)):k.b=f;k.c=d.i(q.a.g,2);f=q.f.icj(k);c=q.bs(c,o);c=q.a6(q.h,c);o=0;q.b.a.i&&(o=4096);e=(new l.cG)._02cG(q.b.a.b,e,g,o);q.a9(e,c,f);e._d()},c:function(){null!=this.h&&this.h.iag(16777248)},ieM:function(q,c){var a=new d._p1(this.d);c.ie1(a,"Faces",
4);this.d=a.a;a=new d._p1(this.f);c.ie4(a,"Shadow2D",!1);this.f=a.a;a=new d._p1(this.g);c.ie4(a,"Conic",!1);this.g=a.a;a=new d._p1(this.a);c.ie4(a,"Inverted",!1);this.a=a.a;a=new d._p1(this.b);c.ie1(a,"Separation",5);this.b=a.a;9<=c.ieQ()&&(a=new d._p1(this.e),c.ie4(a,"DistributeHeight",!1),this.e=a.a)},ie$:function(d){this.h=d},i:function(d){d=d.a;0==d.b&&(d.b=17);0==d.c&&(d.c=1);return null}};A._dt("GP",d.Sy,0,l.icU,l.ieL,l.ie9);var p=function c(){c._ic();this.q=this.u=this.v=!1;this._0_2()};l.VectorPyramid=
p;p.prototype={_0_2:function(){this._bc._0eP.call(this);this.t=4;this.p=5;return this},getConic:function(){return this.v},setConic:function(c){this.v=c;this.r()},getDistributeHeight:function(){return this.u},setDistributeHeight:function(c){this.u=c;this.r()},getFaces:function(){return this.t},setFaces:function(c){this.t=d.a.o(c,3);this.r()},l:function(){return"Pyramid"},getInverted:function(){return this.q},setInverted:function(c){this.q=c;this.r()},getSeparation:function(){return this.p},setSeparation:function(c){this.p=
c;this.r()},icV:function(c,a,b){switch(a){case 4:return 1;case 18:return 1;case 11:return this.y(b)}return null},icW:function(){return 1},icX:function(){return 142737665},icY:function(c,a,b){c.a=1;c.b=0;var i=b.g(256),c=!1;this.a.u()&&(this.e(),this.a.B(null,null),c=!0);a=new l.bh;b.bq(a);i&&(b.bc=!0);var j=b.a.c.iaI(),f=b.k._nc();f.w-=b.a.p;f.y+=b.a.p;f.h-=b.a.p;var t=f.h,o=f.w,k=(t-this.p*(j-1))*f.w/2,e=t/o,g=983040|b.b.l,m=!1;i?m=!0:(g|=134217728,m=!1);0!=this.p&&(g|=3145728);var u=0,h=0,r=0,p=
0;this.q?(u=-t,h=-1,r=f.c(),p=f.y):(u=t,h=1,r=f.y,p=f.c());var n=new l.ba,v=new l.ba;n.b=f.x;n.a=p+h*this.p;n.c=0;v.b=f.g();v.a=r-h*this.p;v.c=b.a.g;p=d.i(f.g()+f.x,2);this.q&&90<b.f.ib5()||!this.q&&90>=b.f.ib5()?(b.C=-1,b.o=j-1,b.e=b.o,b.p=0):(b.C=1,b.o=0,b.e=b.o,b.p=j-1);var i=i?this.t:4,s=0,z=0,x=b.N,A=b.V;if(A){for(var y=x=0;y<j;y++)b.ay(b.d,y,!1),s=b.aj.getItem(b.d,y)*b.aX,x+=s;if(0==x)return}for(y=0;y<j;y++){b.aw();if(A){if(0==b.aX){b.av(0,1);continue}b.J*=b.aX;z+=b.J}else z=b.G;if(0!=b.J&&
1.0E108!=b.J){0>b.C?(this.u?s=t-z/x*t:(s=k-z*k/x,s=d.a.u(d.a.d(2*s*e))),v.a=n.a-h*this.p,n.a=r+h*s):(this.u?s=z/x*t:(s=z*k/x,s=d.a.u(d.a.d(2*s*e))),n.a=v.a+h*this.p,v.a=r+h*s);var s=this.q?f.y-v.a:f.c()-v.a,B=0;b.g(33554432)&&(B|=1);b.ay(b.d,b.e,!1);b.R(!0);b.aE(b.d,b.e);var C=g;y==j-1&&(C|=3145728);m?this.v?b.f.ib9(b.c,n,v,b.A,b.r,null,C,B,u,s):b.f.ick(b.c,n,v,b.A,b.r,null,C,B,u,s,i):this.A(b.c,n._nc(),v._nc(),B,u,s,b);s=b.J/x;b.b.a.a&&this.B(b,a,o,t,n,v,p,r,s)}b.av(0,1)}b.W-=j-1;b.e=b.p;c&&this.a.E();
this.a._dispose1(!1)},B:function(c,a,b,i,j,f,t,o,k){var e=new l.ba,g=c.b.a.h,m=c.b.a.f;c.g(256)&&(g=0);switch(m){case 0:e.a=this.q?f.a:j.a;break;case 2:e.a=this.q?j.a:f.a;break;default:e.a=d.i(j.a+f.a,2)}1!=g?(b=l.bL.a(e.a-o,d.i(b,2),i),e.b=(this.q?0==g:2==g)?t-b:t+b,e.b=2==g?e.b-d.i(c.aP,2):e.b+d.i(c.aP,2)):e.b=t;e.c=d.i(c.a.g,2);t=c.f.icj(e);a=c.bs(a,k);a=c.a6(c.h,a);k=0;c.b.a.i&&(k=4096);g=(new l.cG)._02cG(c.b.a.b,g,m,k);c.a9(g,a,t);g._d()},A:function(c,a,b,i,j,f,t){var o=null,k=null,o=k=null,
e=0,g=0,m=0,u=c=0,h=0,r=0,e=h=g=e=0,c=new l.ba,u=new l.ba;c._cf(a);u._cf(b);k=l.ba._ca(4);o=l.ba._ca(4);l.ba._ca(4);c=d.i(a.b+b.b,2);u=d.i(a.a+b.a,2);h=d.i(a.c+b.c,2);i=0!=(i&8);e=0!=(a.b+b.b&1);i&&(p.x(a,c,u),p.x(b,c,u),a.b>b.b&&(g=new d._p2(a.b,b.b),l.bL.c(g),a.b=g.a,b.b=g.b),e&&b.a--);r=b.a-a.a;e=b.b-a.b;g=b.c-a.c;e=d.i(e,2);g=d.i(g,2);if(0!=j){var w=0,n=0,w=l.bL.a(f,e,j),n=l.bL.a(f,g,j),m=new d._p1(m);p.w(m,4,c,b.a,h,e-w,g-n,k,-1);m=m.a;w=l.bL.a(f+r,e,j);n=l.bL.a(f+r,g,j);f=new d._p1(m);p.w(f,
4,c,a.a,h,e-w,g-n,o,-1)}else{f=new d._p1(m);p.w(f,4,c,b.a,h,e,g,k,b.b);for(h=0;4>h;h++)o[h]._cf(k[h]);for(h=0;4>h;h++)o[h].a=a.a}e=4;f=null;if(0!=j&&(f=d.e._ca(e),f[0].x=k[1].b,f[0].y=b.a,f[1].x=k[3].b,f[1].y=b.a,f[2].y=a.a,f[2].x=o[3].b,f[3].x=o[1].b,f[3].y=a.a,i))for(h=0;h<e;h++)p.z(f[h],c,u);if(b.a!=a.a){a=d.d.b._nc();for(b=this.a.id().Sb();!0==b.SI();)switch(j=b.SK(),j.b){case "P":case "PointsPolygon":j.sa(f);break;default:this.a.l(j,t,this,a)}this.c(t,this.a,d.d.b._nc())}},r:function(){null!=
this.b&&this.b.iag(16777248)},j:function(c,a){var b=new d._p1(this.t);a.ie1(b,"Faces",4);this.t=b.a;b=new d._p1(this.v);a.ie4(b,"Conic",!1);this.v=b.a;b=new d._p1(this.q);a.ie4(b,"Inverted",!1);this.q=b.a;b=new d._p1(this.p);a.ie1(b,"Separation",5);this.p=b.a;b=new d._p1(this.u);a.ie4(b,"DistributeHeight",!1);this.u=b.a},y:function(c){c=c.a;0==c.b&&(c.b=17);0==c.c&&(c.c=1);return null},toString:function(){return"Pyramid"}};p.w=function(c,a,b,i,j,f,l,o,k){for(var e=0,g=0,m=0,p=m=g=0,h=0,r=0,w=0,a=
d.a.o(d.a.d(a),2),a=d.a.p(a,4),w=6.28318530717959/a,p=d.a.t(w),h=d.a.i(w),g=1,e=m=0;e<a;e++)o[e].a=i,o[e].b=b+d.a.k(f*m+0.5),o[e].c=j+d.a.k(l*g+0.5),r=g*h+m*p,m=m*h-g*p,g=r;c.a=w;if(-1!=k){g=d.u.c;m=-1;for(e=0;e<a;e++)o[e].b>g&&(m=e,g=o[e].b);if(-1!=m)for(e=0;e<a;e++)o[e].b==g&&(o[e].b=k)}return a};p.x=function(c,a,b){var d=c.b;c.b=a+(b-c.a);c.a=b-(a-d)};p.z=function(c,a,b){var d=c.x;c.x=a+(b-c.y);c.y=b-(a-d)};p._dt("VV",l.eP,0,l.icU);void 0!==l.UserInterface&&l.UserInterface.prototype.galleryMap["1"].push("14,Pyramid")})();
