(function(){var l=window.sfx,f=window.cfx;f.radarVersion="7.4.5649.31763";var H=function a(){a._ic();this.d=this.e=null;this.a=0};f.bu=H;H.prototype={_0bu:function(){this.k();return this},getCircular:function(){return 0!=(this.a&4)},setCircular:function(a){this.b(4,a)},getClockwise:function(){return 0!=(this.a&32)},setClockwise:function(a){this.b(32,a)},getClosed:function(){return 0!=(this.a&8)},setClosed:function(a){this.b(8,a)},getFillArea:function(){return 0!=(this.a&2)},setFillArea:function(a){this.b(2,
a)},getShadows:function(){return 0!=(this.a&16)},setShadows:function(a){this.b(16,a)},getShowLines:function(){return 0!=(this.a&1)},setShowLines:function(a){this.b(1,a)},icX:function(a,d,b,f){switch(d){case 11:return this.j(b);case 18:return 3}return null},icY:function(a){return 1},icZ:function(a){return 8397382},ic0:function(a,d,b){a.a=1;a.b=0;d=b.a.c.iaI();var m=b.k._nc();if(b.i.getVisible()){var h=new l.g,n=b.i.getLabelsCore();if(0!=n.Se()){var v=new l._p1(!1),n=n.ied(v,b.c,b.i.getFont(),!1);h._cf(n)}else n=
l.b.k(b.bk,"{0}",d),h._cf(b.c.idY(n,b.i.getFont()).e());m.m(-h.w,-h.h)}var g,c=new l._pN(0,0,0,0);f.bL.I(c,m,!0);n=c.a;v=c.b;h=c.c;g=c.d;h=l.a.o(h,1);g=l.a.o(g,1);var p=0!=(b.j&2),e=360/d,k=0,k=b.i.aC()?p?45:e:b.i.getStep();this.getClockwise()||(e=-e,k=-k);m=this.o(b,n,v,h,g,m,k);if(H.m(b,n,v,h,g,k,m,this.getCircular())){for(var m=p?0:-90,k=g=!1,q=0,r=0,t=b.v;t<=b.t;t++)if(b.d=t,b.aL(t),!b.g(8192)){var I=!1,z=0,y=0,x=0,J=0,F=0,G=0,D=0,K=b.N,A=b.J,O=h/(A-K);this.d=null;for(var w=0;w<d;w++){b.e=w;b.ak();
b.U(!0);var k=g,C=b.w;p&&(m=this.getClockwise()?b.aY:-b.aY);c.a=m;f.bO.e(c);m=c.a;if(f.c_.g(C))if(0==w)I=!0;else{if(!f.c_.g(D)){c.Y(q,r);var E=this.c(c,b,x,J,z,y,t,w,w-1,!0,n,v),q=c.a,r=c.b;if(!E&&(g=!0,0==(b.j&1)&&(k=!0),k))break}}else{if(C<=A&&C>=K){var C=C-K,L=E=0,L=E=C*O;c.Y(z,y);f.bO.d(c,m,E,L,n,v);z=c.a;y=c.b;if(0==w||f.c_.g(D))0==w&&(F=z,G=y);else if(c.Y(q,r),x=this.c(c,b,x,J,z,y,t,w,w-1,!1,n,v),q=c.a,r=c.b,!x&&(g=!0,0==(b.j&1)&&(k=!0),k))break}x=z;J=y;if(k)break}D=C;m+=e;b.aj(0,0)}if(k)break;
if(!f.c_.g(D)){b.ab=!1;b.ak();b.U(!0);this.getClosed()||(F=z,G=y);c.Y(q,r);z=this.c(c,b,z,y,F,G,t,b.e,b.e,I,n,v);q=c.a;r=c.b;if(!z){g=!0;break}b.aj(0,0);I||0==(this.a&8)||(b.e=0,b.ab=!1,b.ak(),b.U(!0),c.Y(q,r),this.c(c,b,F,G,F,G,t,0,0,!0,n,v),q=c.a,r=c.b,b.aj(0,0))}}g?(b.d=q,b.e=r,a.b=0,a.a=a.b):(b.Y-=d-1,b.e=b.p)}},o:function(a,d,b,m,h,n,v){var g=a.c,c=a.i,p=a.x(512),e=l.e._ca(3);e[0].x=d;e[0].y=b;var k=this.getCircular(),q=this.getShadows(),r=a.bw(),t=l.a.d(360/v),I=0,z=0,y=0;q&&0!=r.a&&!p?(I=l.i(r.r,
t+1),z=l.i(r.g,t+1),y=l.i(r.b,t+1)):(q=!1,I=z=y=0);var x=c.c.a,J=null,F=0!=(a.u&8),G=null,D=null,K=null;F&&(J=(new f.c2)._01c2("PlotArea"),G=c.a7(x),D=(new f.c2)._01c2(f.c9.aa(c,"Line",-1,!0)),K=(new f.c2)._01c2(f.c9.aa(a.h,"Line",-1,!0)));var A=(new l.ar)._0ar(r),O=a.i.Q.c(l.m.b),w=a.h.Q.c(l.m.b);k&&(q||g.idM(A,n.x,n.y,2*m,2*h));var C=x.v,E=null;C&&(E=a.a_(x,4));var x=c.getLabelsCore(),L=x.Se(),W=c.getFont(),p=p?l.m.c():c.getTextColor()._nc(),B=0!=(a.j&2)?0:270,u=r._nc(),U=A;g.sidd(null);var Q,R,
M=new l._p2(0,0);f.bO.d(M,B,m,h,d,b);Q=M.a;R=M.b;for(var P=0;P<t;P++){var N=c.getVisible();N&&(F&&g.sidd(c),H.n(a,t,x,L,W,p,Q,R,B,P));B+=v;M.a=B;f.bO.e(M);var B=M.a,S=0,T=0;M.Y(S,T);f.bO.d(M,B,m,h,d,b);S=M.a;T=M.b;e[1].x=Q;e[1].y=R;e[2].x=S;e[2].y=T;this.getClockwise()&&f.bL.E(e[1],e[2]);q&&(U=(new l.ar)._0ar(u));F&&g.sidd(J);k?q&&g.idP(U,n,B-v,v):(g.idQ(U,e),g.sidd(D),g.idt(O,Q,R,S,T));q&&U._d();if((0==P||C)&&N){var V=N=null;if(0==P){if(V=K,N=w,4==a.aq||0==a.aq)C?(V=G,N=E):N=null}else V=G,N=E;null!=
N&&(g.sidd(V),g.idt(N,d,b,Q,R),0!=P&&g.sidd(G))}Q=S;R=T;q&&(P>=l.i(t+1,2)?P==t?u._cf(r):u._cf(f.bL.e(r.a,u.r+I,u.g+z,u.b+y)):u._cf(f.bL.e(r.a,u.r-I,u.g-z,u.b-y)))}k&&(F&&g.sidd(D),g.idk(O,n.x,n.y,2*m,2*h));O._d();w._d();null!=E&&E._d();A._d();return t},c:function(a,d,b,m,h,n,v,g,c,p,e,k){var q=a=0;p||(d.aU(v,c,!0),this.getFillArea()&&(p=l.e._ca(3),p[0].x=b,p[0].y=m,p[1].x=h,p[1].y=n,p[2].x=e,p[2].y=k,e=null,0!=(d.u&8)&&(e=d.c.idd(),null==this.d&&(k=(new f.bN)._0bN(d.bR,d.d,d.e,!0,!1,0),k.i=!0,this.d=
k),d.c.sidd(this.d)),d.c.idQ(d.A,p),0!=(d.u&8)&&d.c.sidd(e)),this.getShowLines()&&d.c.idt(d.r,b,m,h,n));a=g;0>d.b.t?(q=-d.b.t,a+=q-1):q=l.a.o(d.b.t,1);0!=d.b.e&&0==a%q&&(0!=(d.j&192)&&d.aA(d.d,c,!1)&&d.U(!0),d.aF(v,c),d.a2(b,m,0));d.c.sidd(null);d.b.a.b&&-1!=c&&(h=0,c!=g&&(h|=2),d.aV((new l.e)._01e(b,m),null,h));return!0},l:function(){null!=this.e&&this.e.iag(16777248)},ieO:function(a,d){if(0!=(d.ieT()&2)){var b=this.a,b=f.bL.b(d,"ShowLines",b,1,!0,!0),b=f.bL.b(d,"FillArea",b,2,!1,!0),b=f.bL.b(d,
"Circular",b,4,!1,!0),b=f.bL.b(d,"Closed",b,8,!0,!0),b=f.bL.b(d,"Clockwise",b,32,!0,!0);this.a=b=f.bL.b(d,"Shadows",b,16,!1,!0)}else this.a=d.ie7(null,this.a,41)},ifa:function(a){this.e=a},k:function(){this.a=41},b:function(a,d){this.a=d?this.a|a:this.a&~a;this.l()},j:function(a){a=a.a;a.e=8;0==a.b&&(a.b=4096);return null}};H.n=function(a,d,b,m,h,n,v,g,c,p){var e=0,k=0;270==c||90==c?e=1:90<=c&&270>=c&&(e=2);k=180<=c?2:0;c=null;c=0!=m?b.iee(p):0!=(a.j&2)?a.i.u.b(360*p/d)+"\u00b0":a.i.u.b(a.i.aC()?
p+1:p*a.i.a3());c=a.a$(a.i,c);d=(new f.cG)._01cG(n,e,k);d.n(a.c,h,c,(new l.e)._01e(v,g));d._d()};H.m=function(a,d,b,m,h,n,v,g){var c=a.N,p=a.J;if(c>=p)return!1;var e=a.h,k=e.o;if(0==(k&64)&&(e.aC()&&e.calculateStep(a.a,a.c,h,!0),h=e.a3(),k=0==(k&1),0<h)){var q=e.u,r=e.getFont(),t=a.x(512),I=e.getLabelsCore(),z=I.Se(),y=t?l.m.c():e.getTextColor()._nc(),x=e.c.a,t=x.v,J=a.a_(x,4),y=(new f.cG)._01cG(y,0,0),F=m/(p-c),G=a.c.idY(q.b(a.J),r).e().h,D=0!=(a.u&8),K=null;D&&(K=e.a7(x));for(var x=0!=x.w,A=0,O=
0,w=c+h;w<=p;w+=h){var C=270,E=0,L=0,L=E=(w-c)*F;if(5>l.a.d(E-m))break;t&&g&&(D&&a.c.sidd(K),a.c.idk(J,d-L,b-L,2*L,2*L));for(var H=0;H<=v;H++){var B=0,u=0,u=new l._p2(B,u);f.bO.d(u,C,E,L,d,b);B=u.a;u=u.b;if(0!=H)if(t&&!g)D&&a.c.sidd(K),a.c.idt(J,A,O,B,u);else break;else k&&(A=null,0!=z?(A=f.bO.a((w-c)/e.X+.1),A=I.iee(A)):A=q.b(w),A=a.a$(e,A),D&&a.c.sidd(e),y.n(a.c,r,A,(new l.e)._01e(B+4,u-l.i(G,2)))),x&&(D&&a.c.sidd(K),a.c.idt(J,B-2,u,B+2,u));C+=n;A=B;O=u}}y._d();J._d()}return!0};H._dt("GR",l.SA,
0,f.icW,f.ieN,f.ie_)})();
