(function(){var r=window.cfx,c=window.sfx,S={Version:"7.3.5518.20383"};r.rose=S;var m=function v(){v._ic()};m.prototype={_0dN:function(){return this}};m.h=function(v){return v*c.a.c/180};m.f=function(v){return c.a.k(v+1.0E-13)};m.e=function(v,h,a){var e=0;a&&(h.w<h.h?(e=c.i(h.h-h.w,2),h.h=h.w,h.y+=e):(e=c.i(h.w-h.h,2),h.w=h.h,h.x+=e));h.w-=h.w%4;h.h-=h.h%4;v.c=c.i(h.w,2);v.d=c.i(h.h,2);v.a=c.i(h.g()+h.x,2);v.b=c.i(h.y+h.c(),2)};m.d=function(c){for(;360<=c.a;)c.a-=360;for(;0>c.a;)c.a+=360};m.a=function(v,
h,a,e,b,j){var g;g=new c._p2(0,0);m.b(g,h,a,e,b,j);h=g.a;g=g.b;v.b=c.a.k(g+0.5);v.a=c.a.k(h+0.5)};m.b=function(v,h,a,e,b,j){var g=m.h(h),h=c.a.t(g),g=c.a.i(g);0==h&&0==g&&(h=0,g=1);v.b=j+e*h;v.a=b+a*g};m.c=function(c,h){var a=c._nc();c._cf(h);h._cf(a)};m._dt("CWGM",c.Sy,0);var Q=function h(){h._ic();this.i=!1;this.c=this.f=0;this.h=!1;this.e=null;this.d=this.b=0;this.g=!1};Q.prototype={_0dO:function(){this.a=new c.e;return this},j:function(c){return this.i?this.f*c-this.d:-(this.d+this.f*c)}};Q._dt("CWGR",
c.Sy,0);var K=function a(){a._ic();this.j=this.a=this.b=null;this._0_1()};S.Rose=K;K.prototype={_0_1:function(){this.c=3;this.g=0;this.f=!0;this.e=90;this.v();return this},getCircular:function(){return 0!=(this.c&2)},setCircular:function(a){this.h(2,a)},getClockwise:function(){return 0!=(this.c&1)},setClockwise:function(a){this.h(1,a)},getInternalRadius:function(){return this.g},setInternalRadius:function(a){this.g=a},n:function(){return 0!=(this.c&4)},sn:function(a){this.h(4,a)},getSideBySide:function(){return this.f},
setSideBySide:function(a){this.f=a},getStartAngle:function(){return this.e},setStartAngle:function(a){this.e=a},getTemplate:function(){return null==this.b?null:this.b.t()},setTemplate:function(a){this.j=a;null==this.b&&(this.b=(new r._Zt)._0_Zt());this.b.st(a)},l:function(a){return this.a.j(a)},icV:function(a,c,b){switch(c){case 11:return this.o(b)}return null},icW:function(){return 1},icX:function(){var a=33579536;this.f&&(a|=128);return a},v:function(){if(void 0!=r._Zt){var a=r.eP.i("Rose",!0);
null!=a&&this.setTemplate(a)}},icY:function(a,e,b){e=b.a.c.iaI();this.a=(new Q)._0dO();this.a.f=360/e;this.a.i=this.getClockwise();this.a.d=this.e;if(null!=this.b&&null!=this.b.t()){this.a.g=!0;for(var j=this.b.id().Sb();!0==j.SI();)switch(j.SK().bA()){case "GT":case "GeometryTop":this.a.h=!0}}j=!1;0!=b.b.d&&(j=!0,this.a.e=Array(e));a.a=1;a.b=0;var g=b.k._nc();if(b.i.getVisible()){var i=new c.g,d=b.i.getLabelsCore();if(0!=d.Se()){var k=new c._p1(!1),d=d.ieb(k,b.c,b.i.getFont(),!1);i._cf(d)}else d=
c.b.k(b.bf,"{0}",e),i._cf(b.c.idW(d,b.i.getFont()).e());g.m(-i.w,-i.h)}var f;f=new c._pN(0,0,0,0);m.e(f,g,!0);d=f.a;k=f.b;i=f.c;f=f.d;i=c.a.o(i,1);f=c.a.o(f,1);this.a.b=c.a.p(i,f);this.a.c=this.g*this.a.b/100;this.a.a._i1(d,k);k=0!=(b.j&2);d=0;d=0>=b.i.F?k?45:360/e:b.i.getStep();this.getClockwise()||(d=-d);g=this.u(b,g,d);if(this.q(b,d,g,this.getCircular())){g=!1;k=d=0;f=!1;for(var l=c.a.p(b.t,b.u),s=c.a.o(b.t,b.u);l<=s;l++)if(b.d=l,b.aL(l),!b.g(8192)){for(var n=b.M,D=b.I,t=(i-this.a.c)/(D-n),o=0;o<
e;o++){b.e=o;b.aw();b.ay(b.d,b.e,!1);b.R(!0);b.aS(b.d,b.e,!1);var p=b.J,w=0;f&&(w=this.a.e[o],p+=w);if(1.0E108==p)p=0;else if(p<=D&&p>=n&&!this.t(b,(w-n)*t,(p-n)*t,f)){d=l;k=o;g=!0;break}j&&(this.a.e[o]=p);b.av(0,1)}j&&(f=!0);if(g)break}g?(b.d=d,b.e=k,a.b=0,a.a=a.b):(b.W-=e-1,b.e=b.p);this.a=null}},u:function(a,e,b){var j=a.c,g=a.i,i=a.x(512),d=c.e._ca(3);d[0]._cf(this.a.a);var k=this.getCircular(),f=this.n(),l=a.bp(),s=c.a.d(360/b),n=0,D=0,t=0;f&&0!=l.a&&!i?(n=c.i(l.r,s+1),D=c.i(l.g,s+1),t=c.i(l.b,
s+1)):(f=!1,n=D=t=0);var o=g.c.a,p=null,w=0!=(a.v&8),q=null,R=null,A=null;w&&(p=(new r.c2)._01c2("PlotArea"),q=g.a7(o),R=(new r.c2)._01c2(r.c9.aa(g,"Line",-1,!0)),A=(new r.c2)._01c2(r.c9.aa(a.h,"Line",-1,!0)));var I=(new c.ar)._0ar(l),z=a.i.Q.c(c.m.b._nc()),O=a.h.Q.c(c.m.b._nc());k&&!a.m_bDetecting&&!f&&(w&&j.sidb(p),j.idK(I,e.x,e.y,2*this.a.b,2*this.a.b));var E=o.v,H=null;E&&(H=a.a8(o,4));var o=g.getLabelsCore(),P=o.Se(),J=g.getFont(),i=i?c.m.c():g.getTextColor()._nc(),x=0!=(a.j&2)?0:270,u=l._nc(),
y=I;j.sidb(null);var B,F,C=new c._p2(0,0);m.a(C,x,this.a.b,this.a.b,this.a.a.x,this.a.a.y);B=C.a;F=C.b;for(C=0;C<s;C++){var M=!a.m_bDetecting&&g.getVisible();M&&(w&&j.sidb(g),K.r(a,s,o,P,J,i,B,F,x,C));x+=b;x=new c._p1(x);m.d(x);var x=x.a,N=0,G=0,G=new c._p2(N,G);m.a(G,x,this.a.b,this.a.b,this.a.a.x,this.a.a.y);N=G.a;G=G.b;d[1].x=B;d[1].y=F;d[2].x=N;d[2].y=G;this.getClockwise()&&m.c(d[1],d[2]);if(!a.m_bDetecting&&(f&&(y=(new c.ar)._0ar(u)),w&&j.sidb(p),k?f&&j.idN(y,e,x-b,b):(j.idO(y,d),j.sidb(R),j.idr(z,
B,F,N,G)),f&&y._d(),(0==C||E)&&M)){F=B=null;if(0==C){if(F=A,B=O,4==a.an||0==a.an)E?(F=q,B=H):B=null}else F=q,B=H;if(null!=B){var M=this.a.a.x,L=this.a.a.y;0!=this.a.c&&(L=new c._p2(M,L),m.b(L,x,this.a.c,this.a.c,this.a.a.x,this.a.a.y),M=L.a,L=L.b);j.sidb(F);j.idr(B,M,L,N,G);0!=C&&j.sidb(q)}}B=N;F=G;f&&(C>=c.i(s+1,2)?C==s?u._cf(l):u._cf(c.m.l(l.a,u.r+n,u.g+D,u.b+t)):u._cf(c.m.l(l.a,u.r-n,u.g-D,u.b-t)))}k&&!a.m_bDetecting&&(w&&j.sidb(R),j.idi(z,e.x,e.y,2*this.a.b,2*this.a.b));z._d();O._d();null!=H&&
H._d();I._d();return s},t:function(a,e,b,j){var g=this.a.c,i=(new c.aA)._0aA(),d=0,k=0;0==g?(d=a.b.v/100,k=(1-d)/2):(d=1,k=0);1!=a.ad&&(d/=a.ad,k+=a.T*d);var f=this.l(a.e+k),l=this.l(a.e+k+d),d=(f+l)/2,s=new c.f,n=new c.f,m=new c.f,t=new c.f,o=2*g,p=this.a.a.x-g,w=this.a.a.y-g,k=new c.f;m._cf(this.d(f,0));t._cf(this.d(l,0));var q=this.d(d,0);k._cf(this.d(d,b));var r=m.x-t.x,A=m.y-t.y;s._i1(k.x+r/2,k.y+A/2);n._i1(k.x-r/2,k.y-A/2);0!=e&&(q._cf(this.d(d,e)),m._i1(q.x+r/2,q.y+A/2),t._i1(q.x-r/2,q.y-A/
2));q=null;this.a.h&&(q=(new c.aA)._0aA());0!=g?(j?(i.r(s,n),i.r(n,t),i.r(t,m)):(i.f((new c.d)._02c(p,w,o,o),l,f-l),i.r(m,s),i.r(s,n)),i.C(),null!=q&&q.r(s,n)):(g=2*b,j?(i.g(this.a.a.x-e,this.a.a.y-e,2*e,2*e,f,l-f),i.g(this.a.a.x-b,this.a.a.y-b,g,g,l,f-l)):(i.u(this.a.a.x,this.a.a.y,t.x,t.y),0<b&&i.g(this.a.a.x-b,this.a.a.y-b,g,g,l,f-l),i.C()),null!=q&&q.g(this.a.a.x-b,this.a.a.y-b,g,g,l,f-l));if(this.a.g){e=c.d.b._nc();for(j=this.b.id().Sb();!0==j.SI();)switch(f=j.SK(),f.bA()){case "G":case "Geometry":f.sa(i);
break;case "GT":case "GeometryTop":f.sa(q);break;case "SizeItem":f.sa(2*b);break;case "XItem":f.sa(this.a.a.x-b);break;case "YItem":f.sa(this.a.a.y-b);break;default:this.b.l(f,a,this,e)}this.b.v(a.c,e,1,0)}else a.c.idM(a.A,i),a.c.idt(a.r,i);if(a.m_bDetecting&&a.detectCheck())return a.j&=-2,!1;i._d();null!=q&&q._d();a.b.a.a&&(b=a.c.ide(),i=new c.aE,i.f(d+90,k),a.c.side(i),a.aZ((new c.e)._01e(k.x,k.y),!1,null),a.c.side(b));return!0},q:function(a,e,b,j){var g=a.M,i=a.I;if(g>=i)return!1;var d=a.h,k=d.o;
if(0==(k&64)&&!a.m_bDetecting){0>=d.F&&d.calculateStep(a.a,a.c,this.a.b,!0);var f=c.a.d(d.F),k=0==(k&1);if(0<f){var l=d.t,s=d.getFont(),n=a.x(512),D=d.getLabelsCore(),t=D.Se(),o=n?c.m.c():d.getTextColor()._nc(),p=d.c.a,n=p.v,w=a.a8(p,4),o=(new r.cG)._01cG(o._nc(),0,0),q=(this.a.b-this.a.c)/(i-g),K=a.c.idW(l.a(a.I),s).e().h,A=0!=(a.v&8),I=null;A&&(I=d.a7(p));for(var p=0!=p.w,z=0,O=0,E=g+f;E<=i;E+=f){var H=270,P=0,J=0,J=P=(E-g)*q+this.a.c;if(5>c.a.d(P-this.a.b))break;n&&j&&(A&&a.c.sidb(I),a.c.idi(w,
this.a.a.x-J,this.a.a.y-J,2*J,2*J));for(var x=0;x<=b;x++){var u=0,y=0,y=new c._p2(u,y);m.a(y,H,P,J,this.a.a.x,this.a.a.y);u=y.a;y=y.b;if(0!=x)if(n&&!j)A&&a.c.sidb(I),a.c.idr(w,z,O,u,y);else break;else if(k&&(z=null,0!=t?(z=m.f((E-g)/d.X+0.1),z=D.iec(z)):z=l.a(E),z=a.a6(d,z),A&&a.c.sidb(d),o.l(a.c,s,z,(new c.e)._01e(u+4,y-c.i(K,2)))),p)A&&a.c.sidb(I),a.c.idr(w,u-2,y,u+2,y);H+=e;z=u;O=y}}o._d();w._d()}}return!0},d:function(a,e){return this.p(new c._p2(0,0),a,e)},p:function(a,e,b){e=e*c.a.c/180;a.a=
c.a.t(e);a.b=c.a.i(e);b+=this.a.c;e=this.a.a.x+b*a.b;a=this.a.a.y+b*a.a;return(new c.f)._01e(e,a)},reset:function(){},ieM:function(a,e){this.c=e.ie5("Flags",this.c,3);var b=new c._p1(this.e);e.ie3(b,"StartAngle",90);this.e=b.a;b=new c._p1(this.g);e.ie2(b,"InternalRadius",0);this.g=b.a;b=new c._p1(this.f);e.ie4(b,"SideBySide",!0);this.f=b.a;b=new c._p1(this.j);e.ieV(b,"Template");this.j=b.a},h:function(a,c){this.c=c?this.c|a:this.c&~a},o:function(a){a.a.e=8;return null}};K.r=function(a,e,b,j,g,i,d,
k,f,l){var m=0,n=0;270==f||90==f?m=1:90<=f&&270>=f&&(m=2);n=180<=f?2:0;f=null;f=0!=j?b.iec(l):0!=(a.j&2)?a.i.t.a(360*l/e)+"\u00b0":a.i.t.a(0>=a.i.F?l+1:l*c.a.d(a.i.F));f=a.a6(a.i,f);e=(new r.cG)._01cG(i._nc(),m,n);e.l(a.c,g,f,(new c.e)._01e(d,k));e._d()};K._dt("rose.Rose",c.Sy,0,r.icU,r.ieL);void 0!==r.UserInterface&&r.UserInterface.prototype.galleryMap["3"].push("=rose.Rose,Rose")})();
