(function(){var f=window.sfx,g=window.cfx;g.surfaceVersion="7.3.5518.20383";var m=function b(){b._ic();this.b=this.f=this.l=this.a=this.e=null;this.d=this.g=!1;this.p=this.k=this.c=0};g.bs=m;m.prototype={_0bs:function(){return this},getColors:function(){return this.a},setColors:function(b){null==b?this.a=null:(this.a=f.m._ca(b.length),b.Sd(this.a,0));this.j(560)},ieg:function(){return!1},ieh:function(){return null},getShowContourLines:function(){return this.g},setShowContourLines:function(b){this.g=
b;this.o()},getShowGridLines:function(){return this.d},setShowGridLines:function(b){this.d=b;this.o()},iei:function(){return null!=this.e?this.e.iT().i==this:!1},getStep:function(){return 0>this.c?0:this.c},setStep:function(b){this.c=b;this.j(560)},i:function(){return null==this.a||0==this.a.length},iej:function(){},iek:function(b,c,a){var e=this.iel();b.a=!0;c.t=e-1;c.u=0;a&&(b=new f._p2(c.t,c.u),g.bL.c(b),c.t=b.a,c.u=b.b);c.q=a?1:-1;c.d=c.t-c.q;c.aL(0);a?this.m(c.c,0,c.b.g,c.b.o._nc(),e):this.m(c.c,
0,c.b.o,c.b.g._nc(),e)},h:function(b,c,a){0>=this.c&&(this.c=-b.a3(),0<=this.c&&(this.c=-f.a.d((a-c)/10)));return f.a.d(this.c)},iel:function(){var b=this.e.iT().q,c,a;a=new f._p2(0,0);b.af(a,!0);c=a.a;a=a.b;c=this.h(b,c,a);return f.a.h((b.u-b.q)/c)},n:function(b,c,a,e,f,g){if(this.g&&!this.d)for(var i=0;i<e;i++){var h=(i+1)%e;a[h].a==a[i].a&&a[i].a==f&&c.ica(b,g,a[h].b,a[h].a,a[h].c,a[i].b,a[i].a,a[i].c)}},iem:function(){return!1},v:function(b,c,a,e,j,k,i){if(!(-1==e||-1==j||-1==k||-1==i)){var h=
b.f,d=g.ba._ca(4),n=g.ba._ca(8),r=b.u<b.t?-1:1,t=b.l.c+g.bL.a(b.ai,b.d,b.a.h),r=t-r*(b.ai+f.i(b.ai,b.a.h)+1);d[0].b=a;d[0].a=j;d[0].c=t;d[1].b=a;d[1].a=k;d[1].c=r;d[2].b=c;d[2].a=i;d[2].c=r;d[3].b=c;d[3].a=e;d[3].c=t;var j=d[0].a>d[1].a&&d[0].a>d[3].a&&d[2].a>d[1].a&&d[2].a>d[3].a||d[0].a<d[1].a&&d[0].a<d[3].a&&d[2].a<d[1].a&&d[2].a<d[3].a,i=b.h,o=b.M,m=b.I,x=this.h(i,o,m),s=b.z;this.t();for(var u=0;u<this.k;u++){var p=this.q(u),p=(new f.ar)._0ar(p),v=this.d?this.f:(new f.ao)._0ao(p),w=this.g&&!this.d?
this.f:null,o=o+x;o>m&&(o=m);var q=s,s=i.aj(b.a,o);q++;if(j){d[1].b=a;d[1].a=k;d[1].c=r;var l=g.bQ.P(d,n,s,q,3);0!=l&&(h.ici(b.c,n,l,p,v),this.n(b.c,h,n,l,q,w));d[1].b=c;d[1].a=e;d[1].c=t;l=g.bQ.P(d,n,s,q,3)}else l=g.bQ.P(d,n,s,q,4);0!=l&&(h.ici(b.c,n,l,p,v),this.n(b.c,h,n,l,q,w));p._d();this.d||v._d()}}},icV:function(b,c,a){switch(c){case 11:return this.r(a);case 13:a.b=1;a.h=!0;break;case 18:return 6}return null},q:function(b){if(this.i())return this.l.e();var c=this.a[b%this.a.length]._nc();c.e()&&
c._cf(this.e.iW(b%this.a.length));return c},icW:function(){return 1},icX:function(b){return 10==b?1079056136:1079064328},ien:function(b,c,a,e,j){j._cf(f.g.b);e=this.e.iT().q;j=e.Z();e=f.a.o(j.a(e.u).length,j.a(e.q).length);e=f.b.u(f.b.b,2*e,57);b.a=!0;return c.idW(e+" - ",a).e()},m:function(b,c,a,e,f){this.i()&&(0!=(b.ic$()&8)&&(b=b.idc(),a=b._Gv("fill",a,"Attribute"+c,0),e=b._Gv("fill",e,"Attribute"+c+"Alt",0)),e.e()&&e._cf(g.bL.ag(a._nc(),0)),this.l=new g.b0(a,e,f))},ieo:function(b,c){b.b=null;
b.a=b.b;b.c=null;b.d=-1;if(c.d==c.u)return!1;c.d+=c.q;b.d=c.d;var a=c.h,e=this.h(a,c.M,c.I),g=a.Z(),k=new f.aQ,i=f.a.o(g.a(a.u).length,g.a(a.q).length),h=a.q+e*c.d,h=g.a(h),h=f.b.u(h,i,32);k.e(h);k.e(" - ");h=a.q+e*(c.d+1);h=g.a(h);h=f.b.u(h,i,32);k.e(h);b.b=k.toString();c.b.f=0;c.b.g._cf(this.q(c.d));c.R(!0);return!0},icY:function(b,c,a){var e=c=0;if(a.aQ){if(null==this.b||this.b.length!=a.a.h+1)this.b=f.e._ca(a.a.h+1);c=this.h(a.h,a.M,a.I);this.k=f.a.d(f.a.h((a.I-a.M)/c));0!=(a.v&8)&&(a.bc=!0)}0==
a.d&&a.e==a.o&&(this.m(a.c,a.d,a.b.g,a.b.o._nc(),this.k),this.f=this.d||this.g?a.r.m():null);c=a.l.b;e=a.E?a.H:-1;if(a.E&&a.d!=a.t&&a.e!=a.o){var g=0,g=a.u<a.t?-1:1;this.v(a,c,this.b[a.d].x,e,this.b[a.d].y,this.p,this.b[a.d-g].y)}this.p=this.b[a.d].y;this.b[a.d].x=c;this.b[a.d].y=e;b.a=1;b.b=0;a.d==a.u&&a.e==a.p&&this.u()},o:function(){this.j(32)},j:function(b){null!=this.e&&this.e.iag(b|16777216)},u:function(){null!=this.f&&(this.f._d(),this.f=null)},t:function(){this.i()&&this.l.d()},ieM:function(b,
c){var a=new f._p1(this.g);c.ie4(a,"ShowContourLines",!1);this.g=a.a;a=new f._p1(this.d);c.ie4(a,"ShowGridLines",!1);this.d=a.a;this.a=c.ie6("Colors",this.a,null,96)},ie$:function(b){this.e=b},r:function(b){b.a.e=64;return null}};m._dt("GS",f.Sy,0,g.icU,g.ief,g.i_n,g.ieL,g.ie9)})();
