(function(){var c=window.cfx,d=window.sfx,m={Version:"7.3.5518.20383"};c.heatmap=m;var k=function r(){r._ic();this.b=this.c=0;this._0_1()};m.ColorGradientStop=k;k.prototype={_0_1:function(){this.d=new d.m;this.a=new d.m;return this},getColor:function(){return this.d},setColor:function(c){c=d.m._t(c);this.d._cf(c);this.a._cf(c)},getOffset:function(){return this.c},setOffset:function(d){this.c=d},ieM:function(c,n){n.ieW("Color",this.d);var a=new d._p1(this.c);n.ie3(a,"Offset",0);this.c=a.a}};k._dt("heatmap.ColorGradientStop",
d.Sy,0,c.ieL);var o=function n(){n._ic()};m.ColorGradientCollection=o;o.prototype={_0_1:function(){this.a=(new d._L)._0_L();return this},getCount:function(){return this.a.Se()},getItem:function(d){return this.a.So(d)},setItem:function(d,a){this.a.sSo(d,a)},add:function(d){this.a.Si(d)},clear:function(){this.a.clear()},e:function(c){var a=this.a.Se(),e=this.a.So(0);if(c==e.b)return e.a;for(var b=1;b<a;b++){var h=this.a.So(b),f=h.b;if(f==c)return h.a;if(f>c)return b=f-e.b,a=(c-e.b)/b,c=(f-c)/b,e=e.a._nc(),
h=h.a._nc(),d.m.k(e.r*c+h.r*a,e.g*c+h.g*a,e.b*c+h.b*a);e=h}return e.a},Sb:function(){return this.a.getEnumerator()},insert:function(d,a){this.a.Sl(d,a)}};o._dt("heatmap.ColorGradientCollection",d.Sy,0,d.Sa);var q=function a(){a._ic();this.e=this.c=null;this.i=this.j=this.b=this.f=this.d=this.u=0;this.n=null;this.q=this.r=this.t=0;this._0_1()};m.HeatMap=q;q.prototype={_0_1:function(){this.a=(new o)._0_1();this.g=3;var a=new k;a.setColor(d.m.k(192,0,0));this.a.add(a);a=new k;a.setColor(d.m.k(0,192,
0));this.a.add(a);this.h=60;this.v();void 0!==c.motif?c._Em("heatmap",this,arguments):1<=arguments.length&&this.setStyle(arguments[0]);return this},getGradientStops:function(){return this.a},ieg:function(){return!1},ieh:function(){return null},getLegendHeight:function(){return this.g},setLegendHeight:function(a){this.g=a},iei:function(){return!0},getTemplate:function(){return null==this.e?null:this.e.q},setTemplate:function(a){this.n=a;null==this.e&&(this.e=(new c._Zt)._0_Zt());this.e.st(a)},ic0:function(){},
iej:function(){},icq:function(a){this.c=d.V.D(a,c.Chart);null!=this.c&&this.c.getLegendBox().getItemAttributes().getItemList(this.c.getSeries()).setVisible(!1);return!0},iek:function(){this.d=0},ic1:function(){return!0},ic2:function(){this.l();return!1},iel:function(){return this.m()?1:this.g},iem:function(){return!1},icV:function(a,e,b){switch(e){case 11:return this.p(b);case 13:b.b=1}return null},getHighlightArgs:function(){return!1},k:function(a){return this.c.getAxisY().getDataFormat().a(a)},
icW:function(){return 1},icX:function(){return 20480},ien:function(a,e,b,h,f){a.a=!0;f._cf(d.g.b);a=e.idW(this.k(this.f),b).e();this.m()&&(e=e.idW(this.k(this.b),b).e(),this.i=d.a.o(a.w,e.w),a.w=2*this.i+this.h,a.w=0.8*h.w,this.h=a.w-2*this.i);return a},icr:function(){return null},_iCommands:function(){return!1},v:function(){if(void 0!=c._Zt){var a=c.eP.i("HeatMap",!0);null!=a&&this.setTemplate(a)}},m:function(){var a=this.c.getLegendBox().ibN();return 3==a||1==a},ieo:function(a,e){a.a=null;var b=
0==this.d?this.f:this.b;a.b=0==this.d||this.d==this.g-1?this.k(b):" ";a.c=null;a.d=this.d;var h=this.m(),b=this.g;h&&(b=1);if(this.d>=b)return!1;e.b.f=0;if(0==this.d){var f=e.H,c=e.H+b*e.aP-e.y,g=e.al;e.c.sidb(null);var b=new d.c,i=new d.e,l=new d.e;h?(g+=this.i,l._i1(g,f),i._i1(g+this.h,f),b._i2(g,f,this.h,c-f+2)):(g-=6,i._i1(g,f),l._i1(g,c),b._i2(g,f+1,16,c-f-2));f=(new d.aC)._0aC(i,l,this.a.getItem(1).a,this.a.getItem(0).a);c=this.a.getCount();if(2<c){for(var g=(new d.ax)._01ax(c),i=d.m._ca(c),
l=Array(c),p=0;p<c;p++){var k=this.a.getItem(c-1-p),m=p;i[m]._cf(k.a);l[m]=1-k.b}g.sb(i);g.sc(l);f.sk(g)}e.c.idQ(f,b);f._d();f=this.c.iK(3)._nc();f=(new d.ao)._01ao(f);e.c.idA(f,b);f._d();h&&(h=new d.at,h.sd(1),f=e.b.a.d,c=(new d.ar)._0ar(e.b.a.b),g=d.i(b.y+b.c(),2),e.c.idF(a.b,f,c,b.g()+4,g,h),i=this.k(this.b),h.sb(2),e.c.idF(i,f,c,b.x-4,g,h),a.b="",c._d(),h._d())}this.d++;return!0},icY:function(a,e,b){e=b.c;a.b=1;a.a=0;a=0!=(b.v&8);if(b.e==b.o&&b.d==b.t){0==this.j&&this.l();this.t=d.i(b.k.w,d.a.d(b.p-
b.o)+1);this.u=d.i(b.k.h,d.a.d(b.u-b.t)+1);this.r=b.k.x;this.q=b.k.y;for(var h=!0,f=this.a.getCount(),j=e.idb(),g=0;g<f;g++){var i=this.a.getItem(g),l=i.d._nc();if(a){var k=(new c.c2)._01c2("HeatMap"+g.toString());e.sidb(k);l=e.idc()._Gv("fill",l,null,0)}i.a._cf(l);i.b=i.c;0!=i.b&&(h=!1)}a&&e.sidb(j);if(h&&1<f){j=h=1/(f-1);for(g=1;g<f;g++)i=this.a.getItem(g),i.b=j,j+=h}}if(!(b.U||b.w<this.b))if(g=b.h,h=b.i,f=d.a.k(g.valueToPixel(b.d)),g=d.a.k(g.valueToPixel(b.d+1)),i=d.a.k(h.valueToPixel(b.e+0.5)),
h=d.a.k(h.valueToPixel(b.e+1.5)),!(g<f)){a&&(a=(new c.c2)._01c2(null),j=e.ida().ieB(b.c.idb()),a.d=j.ifg(1),a.e=j.ifg(0),e.sidb(a));b=this.a.e((b.w-this.b)/this.j)._nc();b=(new d.ar)._0ar(b);a=(new d.d)._02c(i,f,h-i,g-f);if(null!=this.e){for(f=this.e.id().Sb();!0==f.SI();)switch(g=f.SK(),g.b){case "F":case "Fill":g.sa(b)}this.e.v(e,a,1,0)}else e.idR(b,a);b._d()}},l:function(){var a=this.c.getAxisY(),e=a.getLabels();e.clear();e.add("");for(var b=this.c.getSeries().Sb();!0==b.SI();){var c=b.SK().getText();
null==c&&(c="");e.add(c)}a.setMin(e.Se()-1);a.setMax(0);a.setLabelValue(1);a.setStyle(a.o|512);this.b=d.D.c;this.f=d.D.d;a=this.c.l;e=a.iaN();b=a.iaI();for(c=0;c<e;c++)for(var f=0;f<b;f++){var j=a.getItem(c,f);1.0E108!=j&&(this.b=d.a.p(this.b,j),this.f=d.a.o(this.f,j))}this.j=this.f-this.b},reset:function(){},ic3:function(){return!1},ieM:function(a,c){var b=new d._p1(this.g);c.ie1(b,"LegendHeight",3);this.g=b.a;b=new d._p1(this.n);c.ieV(b,"Template");this.n=b.a;this.a=c.ie6("GradientStops",this.a,
"ColorGradientCollection",4)},p:function(a){a=a.a;a.e=8;0==this.j&&this.l();a.f=this.b;a.g=this.f;0==a.b&&(a.b=35);return null},ic4:function(){return!1}};q._dt("heatmap.HeatMap",d.Sy,0,c.icp,c.icU,c.icZ,c.ief,c.i_n,c.ieL)})();
