(function(){var o=window.cfx,f=window.sfx,z={Version:"7.3.5518.20383"};o.funnel=z;var t=function A(){A._ic();this.b=this.c=0};t.prototype={_0dM:function(j,c){j.x==c.x?(this.b=j.x,this.c=f.D.e):(this.b=(c.y-j.y)/(c.x-j.x),this.c=c.y-this.b*c.x);return this},a:function(j){return 0==this.b?0:f.D.h(this.c)?this.b:(j-this.c)/this.b}};t._dt("CWGF",f.Sy,0);var j=function c(){c._ic();this.r=null;this.q=!1;this.x=this.g=this.h=this.b=null;this.a=this.u=this.e=this.f=0;this._0_1()};z.Funnel=j;j.prototype={_0_1:function(){this.p=
4;this.c=5;this.i=30;this.m=10;this.d=this.v=!0;this.n=this.j=!1;this.o=(new o.Line)._01_2(9);this.F();return this},getConic:function(){return this.q},setConic:function(c){this.q=c;this.k()},getFaces:function(){return this.p},setFaces:function(c){this.p=f.a.o(c,3);this.k()},getLabelInside:function(){return this.j},setLabelInside:function(c){this.j=c;this.k()},getLabelLine:function(){return this.o},getLabelLineAsSeries:function(){return this.n},setLabelLineAsSeries:function(c){this.n=c;this.k()},getSeparation:function(){return this.c},
setSeparation:function(c){this.c=c;this.k()},getTemplate:function(){return null==this.b?"":this.b.t()},setTemplate:function(c){this.x=c;null==c?this.b=null:(null==this.b&&(this.b=(new o._Zt)._0_Zt()),this.b.st(c))},getTipHeight:function(){return this.i},setTipHeight:function(c){this.i=c},getTipWidth:function(){return this.m},setTipWidth:function(c){this.m=c},H:function(){},icV:function(c,b,a){switch(b){case 4:return 1;case 11:return this.A(a);case 12:return!0;case 18:return 1}return null},icW:function(){return 1},
icX:function(){return 142622977},G:function(c,b){var a=f.i(b.x+b.g(),2),h=this.m*b.w/100;this.f=a-h/2;this.e=a+h/2;a=b.h-this.c*(c.a.c.iaI()-1);this.a=b.c()-a*this.i/100;this.u=c.bz*this.i/100;a=this.d?b.y:b.c();this.h=(new t)._0dM((new f.e)._01e(b.x,a),(new f.e)._01e(this.f,this.a));this.g=(new t)._0dM((new f.e)._01e(b.g(),a),(new f.e)._01e(this.e,this.a))},F:function(){if(void 0!=o._Zt){var c=o.eP.i("Funnel",!0);null!=c&&this.setTemplate(c)}},E:function(c,b){var a=!1,h=b[0].y,g=b[2].y,d=b;if(c.bn<
this.u||0==c.bz){if(h<this.a&&b[2].x==b[3].x)return d=f.e._ca(6),d[0]._i1(this.g.a(h),h),d[1]._i1(this.h.a(h),h),d[2]._i1(this.h.a(this.a),this.a),d[3]._i1(d[2].x,g),d[5]._i1(this.g.a(this.a),this.a),d[4]._i1(d[5].x,g),d;b[0]._i1(this.f,h);b[1]._i1(this.e,h);a=!0}c.aW<this.u?(b[2]._i1(this.e,g),b[3]._i1(this.f,g)):a&&this.a<g?(d=f.e._ca(6),d[0]._i1(this.g.a(h),h),d[1]._i1(this.h.a(h),h),d[2]._i1(this.f,this.a),d[3]._i1(this.f,g),d[4]._i1(this.e,g),d[5]._i1(this.e,this.a)):(b[0]._i1(this.g.a(h),h),
b[1]._i1(this.h.a(h),h),b[2]._i1(this.h.a(g),g),b[3]._i1(this.g.a(g),g));return d},icY:function(c,b,a){c.a=1;c.b=0;var h=a.g(256);h&&(a.bc=!0);c=a.a.c.iaI();b=a.k._nc();b.w-=a.a.p;b.y+=a.a.p;b.h-=a.a.p;if(a.b.a.a&&!this.j){for(var g=0,d=0;d<c;d++){a.J=a.aj.getItem(a.d,d);var j=a.bF(),j=a.c.idW(j,a.af).w,g=f.a.o(g,j)}g+=8;2!=a.b.a.h&&(b.x+=g);b.w-=g}var g=b.h,j=b.w,m=(g-this.c*(c-1))*b.w/2,n=g/j,e=983040|a.b.l,i=!1;h?i=!0:(e|=134217728,i=!1);0!=this.c&&(e|=3145728);var k=0,q=0,s=0,d=0;this.d?(k=-g,
q=-1,s=b.c(),d=b.y):(k=g,q=1,s=b.y,d=b.c());var l=new o.ba,r=new o.ba;l.b=b.x;l.a=d+q*this.c;l.c=0;r.b=b.g();r.a=s-q*this.c;r.c=a.a.g;var B=f.i(b.g()+b.x,2);this.d&&90<a.f.ib5()||!this.d&&90>=a.f.ib5()?(a.C=-1,a.o=c-1,a.e=a.o,a.p=0):(a.C=1,a.o=0,a.e=a.o,a.p=c-1);var h=h?this.p:4,p=0,v=0,u=a.N,t=a.V;if(t){for(d=u=0;d<c;d++)a.ay(a.d,d,!1),p=a.aj.getItem(a.d,d)*a.aX,u+=p;if(0==u)return}a.bz=u;this.G(a,b);for(d=a.bn=0;d<c;d++){a.aw();if(t){if(0==a.aX){a.av(0,1);continue}a.J*=a.aX;v+=a.J}else v=a.G;a.aW=
v;if(0!=a.J&&1.0E108!=a.J){0>a.C?(this.v?p=g-v/u*g:(p=m-v*m/u,p=f.a.u(f.a.d(2*p*n))),r.a=l.a-q*this.c,l.a=s+q*p):(this.v?p=v/u*g:(p=v*m/u,p=f.a.u(f.a.d(2*p*n))),l.a=r.a+q*this.c,r.a=s+q*p);var p=this.d?b.y-r.a:b.c()-r.a,x=0;a.g(33554432)&&(x|=1);a.ay(a.d,a.e,!1);a.R(!0);a.aE(a.d,a.e);var y=e;d==c-1&&(y|=3145728);i?this.q?a.f.ib9(a.c,l,r,a.A,a.r,null,y,x,k,p):a.f.ick(a.c,l,r,a.A,a.r,null,y,x,k,p,h):this.C(a.c,l._nc(),r._nc(),x,k,p,a);p=a.J/u;a.b.a.a&&this.D(a,j,g,l,r,B,s,p,b);a.bn=v}a.av(0,1)}this.H(a,
b);a.W-=c-1;a.e=a.p;null!=this.b&&this.b._dispose1(!1)},D:function(c,b,a,h,g,d,w,m,n){if(!c.V){var e=new o.ba,m=c.b.a._nc(),i=m.h,k=m.f;c.g(256)&&(i=0);switch(k){case 0:e.a=this.d?g.a:h.a;break;case 2:e.a=this.d?h.a:g.a;break;default:e.a=f.i(h.a+g.a,2)}h=c.bF();this.j?1!=i?(n=j.l(e.a-w,f.i(b,2),a),e.b=(this.d?0==i:2==i)?d-n:d+n,e.b=2==i?e.b-f.i(c.aP,2):e.b+f.i(c.aP,2)):e.b=d:(d=k=0,2==i?(e.b=n.g(),d=-2,k=e.a>this.a?this.e:this.g.a(e.a),k+=4,i=0):(e.b=n.x,d=2,k=e.a>this.a?this.f:this.h.a(e.a),k-=4,
i=2),0!=this.o.d?(n=f.m.b._nc(),this.n&&n._cf(c.r.d()),n=this.o.c(n._nc()),c.c.idr(n,k,e.a,e.b+d,e.a),n._d()):e.b=k,k=1);e.c=f.i(c.a.g,2);e=c.f.icj(e);h=c.a6(c.h,h);n=0;m.i&&(n=4096);m=(new o.cG)._02cG(m.b._nc(),i,k,n);c.a9(m,h,e._nc());m._d()}},C:function(c,b,a,h,g,d,w){var m=null,n=null,m=n=null,e=0,i=0,k=0,q=0,s=0,l=0,r=0,e=l=i=e=0,q=new o.ba,s=new o.ba;q._cf(b);s._cf(a);n=o.ba._ca(4);m=o.ba._ca(4);o.ba._ca(4);q=f.i(b.b+a.b,2);s=f.i(b.a+a.a,2);l=f.i(b.c+a.c,2);h=0!=(h&8);e=0!=(b.b+a.b&1);h&&(j.w(b,
q,s),j.w(a,q,s),b.b>a.b&&(i=new f._p2(b.b,a.b),j.z(i),b.b=i.a,a.b=i.b),e&&a.a--);r=a.a-b.a;e=a.b-b.b;i=a.c-b.c;e=f.i(e,2);i=f.i(i,2);if(0!=g){var t=0,p=0,t=j.l(d,e,g),p=j.l(d,i,g),k=new f._p1(k);j.t(k,4,q,a.a,l,e-t,i-p,n,-1);k=k.a;t=j.l(d+r,e,g);p=j.l(d+r,i,g);d=new f._p1(k);j.t(d,4,q,b.a,l,e-t,i-p,m,-1)}else{d=new f._p1(k);j.t(d,4,q,a.a,l,e,i,n,a.b);for(l=0;4>l;l++)m[l]._cf(n[l]);for(l=0;4>l;l++)m[l].a=b.a}e=4;d=null;if(0!=g&&(d=f.e._ca(e),d[0].x=n[1].b,d[0].y=a.a,d[1].x=n[3].b,d[1].y=a.a,d[2].y=
b.a,d[2].x=m[3].b,d[3].x=m[1].b,d[3].y=b.a,h))for(l=0;l<e;l++)j.B(d[l],q,s);if(a.a!=b.a)if(d=this.E(w,d),b=f.d.b._nc(),null!=this.b){for(c=this.b.id().Sb();!0==c.SI();)switch(a=c.SK(),a.bA()){case "P":case "PointsPolygon":a.sa(d);break;default:this.b.l(a,w,this,b)}c=f.d.b._nc();this.b.v(w.c,c,1,0)}else c.idO(w.A,d),c.idv(w.r,d)},k:function(){null!=this.r&&this.r.iag(16777248)},reset:function(){},ieM:function(c,b){var a=new f._p1(this.p);b.ie1(a,"Faces",4);this.p=a.a;a=new f._p1(this.c);b.ie1(a,"Separation",
5);this.c=a.a;a=new f._p1(this.i);b.ie3(a,"TipHeight",30);this.i=a.a;a=new f._p1(this.m);b.ie3(a,"TipWidth",10);this.m=a.a;a=new f._p1(this.x);b.ieV(a,"Template");this.x=a.a;a=new f._p1(this.q);b.ie4(a,"Conic",!1);this.q=a.a;a=new f._p1(this.j);b.ie4(a,"LabelInside",!1);this.j=a.a;a=new f._p1(this.n);b.ie4(a,"LabelLineAsSeries",!1);this.n=a.a},ie$:function(c){this.r=c;this.o.ie$(this.r)},A:function(c){c=c.a;0==c.b&&(c.b=1);0==c.c&&(c.c=1);return null},toString:function(){return"Funnel"}};j.l=function(c,
b,a){return f.i(c*b,a)};j.t=function(c,b,a,h,g,d,j,m,n){for(var e=0,i=0,k=0,q=k=i=0,o=0,l=0,r=0,b=f.a.o(f.a.d(b),2),b=f.a.p(b,4),r=6.28318530717959/b,q=f.a.t(r),o=f.a.i(r),i=1,e=k=0;e<b;e++)m[e].a=h,m[e].b=a+f.a.k(d*k+0.5),m[e].c=g+f.a.k(j*i+0.5),l=i*o+k*q,k=k*o-i*q,i=l;c.a=r;if(-1!=n){i=f.u.c;k=-1;for(e=0;e<b;e++)m[e].b>i&&(k=e,i=m[e].b);if(-1!=k)for(e=0;e<b;e++)m[e].b==i&&(m[e].b=n)}return b};j.w=function(c,b,a){var f=c.b;c.b=b+(a-c.a);c.a=a-(b-f)};j.B=function(c,b,a){var f=c.x;c.x=b+(a-c.y);c.y=
a-(b-f)};j.z=function(c){var b=c.a;c.a=c.b;c.b=b};j._dt("funnel.Funnel",f.Sy,0,o.icU,o.ieL,o.ie9);void 0!==o.UserInterface&&o.UserInterface.prototype.galleryMap["1"].push("=funnel.Funnel,Funnel")})();
